### ISSUE TITLE
Gen.string(maxSize = 1)  - Generates Only Empty Strings

### ISSUE THREAD

**Issue by EarthCitizen** [kotest/kotest#1004]
v3.4.0

`Gen.string(maxSize = 1)`

Expected:

- Some empty strings
- Some strings with one character

Actual:

- Only empty strings despite running it 100,000 times

**Comment by kortov** [comment]
I guess it's because in https://github.com/kotlintest/kotlintest/blob/6df536e595329358df07aa766a867f635c328ce1/kotlintest-assertions/src/commonMain/kotlin/io/kotlintest/properties/gens.kt#L29 
r.nextInt is exclusive at the end and if I'm not mistaken, Gen.string() should give 99 maxlength by default but I'm not sure.

**Comment by sksamuel** [comment]
Yeah good spot, should be max - min + 1 for the bound.

**Comment by sksamuel** [comment]
Fixed in master, and will be included in 3.4.3 release.
