### ISSUE TITLE
Latest arrow release

### ISSUE THREAD

**Issue by gasch** [kotest/kotest#1026]
Please upgrade all modules to arrow-0.10.0. It seems to be that the assertions module is still on 
version 0.9.
Thank you in advance.

**Comment by LeoColman** [comment]
You can pick this up if you want to :)

**Comment by lenguyenthanh** [comment]
I think all modules use the same arrow version `0.10.0` from here: https://github.com/kotlintest/kotlintest/blob/master/build.gradle#L3.

I searched here: https://github.com/kotlintest/kotlintest/search?l=Gradle&q=arrow. And it looks correct.

**Comment by JYCabello** [comment]
If I reference 3.42, I get typeclasses and core-extensions.
![image](https://user-images.githubusercontent.com/11141026/66115412-11bc7600-e5d1-11e9-859e-70b9aaac02d1.png)
If I reference 3.3.1, I don't.
![image](https://user-images.githubusercontent.com/11141026/66115470-2f89db00-e5d1-11e9-9567-36be488cc956.png)
And I'm just using this package.
`testImplementation("io.kotlintest", "kotlintest-runner-junit5", kotlinTestVersion)`

This creates a heavy collision in the classpath, since Either.fx gets confused and tries to use a Continuation that is no longer there in 0.10.0.
```
java.lang.NoClassDefFoundError: arrow/core/Continuation
	at java.lang.ClassLoader.defineClass1(Native Method)
```

**Comment by lenguyenthanh** [comment]
I think kotlintest 3.4.2 still uses Arrow version 0.9.0. The snapshot version uses Arrow version 0.10.0.

**Comment by yeraytba** [comment]
But, should it expose it?
For the assertions is unavoidable, I understand, but we had to downgrade in order to move forward with this.
And we had to do our own assertions for Options, which was not a big deal.

**Comment by JYCabello** [comment]
But, should it expose it?
For the assertions is unavoidable, I understand, but we had to downgrade in order to move forward with this.
And we had to do our own assertions for Options, which was not a big deal.

**Comment by JYCabello** [comment]
And just learned how to exclude. Not a problem anymore.

**Comment by gasch** [comment]
@JYCabello How did you do it?

**Comment by JYCabello** [comment]
@gasch Sorry, I thought I had replied this already (immediately), seems like I didn't hit `Comment`.
```
    testImplementation("io.kotlintest", "kotlintest-runner-junit5", kotlinTestVersion) {
        exclude("io.arrow-kt")
    }
```

**Comment by sksamuel** [comment]
In 4.0 (master, unreleased) the dependency on arrow is only in the assertions module. So whatever version you use in your project won't affect kotlintest itself.

Marking this as closed. We will do a 3.4.3 with arrow 0.10.x as well.

**Comment by JYCabello** [comment]
Fantastic, thanks!
I'm any case, just excluding works, since the contract of the monads is not broken.
