### ISSUE TITLE
afterTest in BehaviorSpec test runs after each Given, When and Then

### ISSUE THREAD

**Issue by dannylagrouw** [kotest/kotest#1192]
I use BehaviorSpec and wanted to add some cleanup to be run after each individual test (Given {} block). However, it looks like `afterTest` is called after each Given, When and Then block (in reverse order). Is this intentional?

**Comment by sksamuel** [comment]
It should call the inner most block afterTest first. Are you just wanting it to run for Given ?

**Comment by dannylagrouw** [comment]
Yes, I consider a test to be a complete block of Given { When { Then {} } }, so I would expect afterTest to run after each instance of that has run.

**Comment by sksamuel** [comment]
You can use the beforeTest callback to check for the name of the test, and just filter on starts with "Given"

**Comment by dannylagrouw** [comment]
Ok, thanks for the workaround. Don't you agree it would be more intuitive if `afterTest` ran just once after each `given` block?

**Comment by sksamuel** [comment]
Yes and no :)

People lay out tests in all kinds of ways so its not possible to only run afterTest for a particular layout without someone else saying it's now broken for them. It's safer to always run afterTest, since in Kotest every scope is a test.

You can achieve what you want without testing for strings by doing this inside beforeTest:

````
         if (testCase.isTopLevel()) {
            
         }
```

Only `Given` blocks of BehaviorSpec will be true for top level.

**Comment by jadenjack** [comment]
With kotest v5.5.4

```
if (testCase.isRootTest()) {

}
```
