### ISSUE TITLE
Add arb that generates lists

### ISSUE THREAD

**Issue by dump247** [kotest/kotest#1253]
Proposal to add a property test arb that generates lists of values.

Proposed API

```kotlin
fun <A> Arb<A>.chunked(size: IntRange): Arb<List<A>>
fun <A> Arb<A>.chunked(minSize: Int, maxSize: Int): Arb<List<A>>
```

**Comment by dump247** [comment]
I am happy to implement this. I just wanted to get feedback before submitting an MR.

**Comment by sksamuel** [comment]
There is `Arb.Companion.list(gen: Gen<A>, range: IntRange = 0..100)` already which I guess does hte same thing. You could delegate to this, or vice versa. I'm happy to add the new syntax.

**Comment by dump247** [comment]
@sksamuel I did not see that method. Thank you for pointing it out.

Is this (and `list`) something that could or should be added to Gen rather than Arb? It's not entirely clear to me when a method should be added to Arb vs Gen, but this seems like something that would fit on Gen.

**Comment by dump247** [comment]
A related question: `ListShrinker` does not take the min and max size into account when shrinking the list. I think the same thing applies to StringShrinker. Is this intentional?

**Comment by sksamuel** [comment]
The shrinkers should take it into account. I guess the max doesn't matter as it's never going to shrink larger, but definitely min @dump247

**Comment by sksamuel** [comment]
> @sksamuel I did not see that method. Thank you for pointing it out.
> 
> Is this (and `list`) something that could or should be added to Gen rather than Arb? It's not entirely clear to me when a method should be added to Arb vs Gen, but this seems like something that would fit on Gen.

I am thinking about tweaking the interfaces for beta2 and having Gen just be a marker interface with no methods. @Kerooker suggested this a while ago because at the moment the Exhaustive interface doesn't really do much other than be a marker itself.

**Comment by sksamuel** [comment]
@dump247 what are your thoughts on that ?

**Comment by dump247** [comment]
I do not really understand what marker interface means. Does that mean you remove `minIterations` and `generate` from Gen and it has no methods? Or that Gen and Exhaustive do not have any extension methods declared in kotest (everything is on Arb)?

**Comment by sksamuel** [comment]
Exactly. Gen is just an interface to stop you passing Wibble to the forAll
methods. Wherever we do gen.generate at the moment, which is not in many
places, we just wrap it in a when. In other words we treat Exhaustive and
Arb as an ADT.

**Comment by dump247** [comment]
Would forAll (and others) treat Exhaustive differently than Arb? Are these two interfaces more than just generating a sequence of values? What does Gen being a marker interface enable?

It sounds ok to me. It would make the question of where things go a little clearer, I think. I am curious about the reasoning and would like some more details on the thinking behind the change.

**Comment by sksamuel** [comment]
Arb and Ex are two interfaces which are naturally very similar. But Ex requires plain values, and Arb requires values + shrinks + edgecases.

So the options are. 
1) What we have currently - a Gen interface that defines the methods that Arb needs, and Exhaustive just adheres to that.
2) Arb and Exhaustive having the methods that make sense for them, and a marker interface that they both implement.

Either way, forAll takes Gens so that you can pass in arbs and exhaustives and nothing else. The difference would be with 2) that the Exhaustive interface is clearer, at the cost of internally with forAll doing a when to pull values out rather than calling a method.

I'd really consider making Gen a sealed class, that would be the best way, a genuine ADT,  but then Arbs and Exhaustives cannot extend a parent class (I don't know if that's too restrictive).

**Comment by sksamuel** [comment]
I am closing this as the PR is up and it is unrelated to this now completed ticket.
