### ISSUE TITLE
threads and invocations in TestCaseConfig for tests in ContextScope

### ISSUE THREAD

**Issue by crazyk2** [kotest/kotest#1369]
I found this restrictions
1)
```kotlin
      if (testCase.config.invocations > 1 && testCase.type == TestType.Container)
         error("Cannot execute multiple invocations in parent tests")
```
2)
```kotlin
   require(threads <= invocations) { "Number of threads must be <= number of invocations" }
```
3)
```kotlin
inner class TestBuilder(val name: String) {
         @OptIn(ExperimentalTime::class)
         suspend fun config(
//there are not two parameters: invocations and threads
            enabled: Boolean? = null,
            tags: Set<Tag>? = null,
            timeout: Duration? = null,
            extensions: List<TestCaseExtension>? = null,
            enabledIf: EnabledIf? = null,
            test: suspend TestContext.() -> Unit
         ) 
```
it means that tests in context  cann't run in parallel mode.
Question is "why"?

**Comment by sksamuel** [comment]
The inner test can. But the outer test can't because it will cause the
actual "test scope" to be added multiple times, and break the way tests are
registered with junit.

**Comment by crazyk2** [comment]
> The inner test can.

What do you mean? It would be great if you write example (code)

**Comment by sksamuel** [comment]
```kotlin
class MyTest : DescribeSpec({
  describe("some test").invocations(4) {
    it("nested).invocations(2) {
    }
 }
}
```

This is super difficult to support as the inner test will run 8 times, twice each for the 4 outer tests. Then we need to support things like isolation mode while running concurrently.

It's just a huge added complexity for zero gain. You can easily structure your tests to avoid this. So only the inner test scope allows invocations and threads.

BUT the DSL should stop you doing it if possible, so that's something to consider.

**Comment by sksamuel** [comment]
I think ticket #1370 covers the change that needs to happen.
