### ISSUE TITLE
Docs update for IntelliJ productivity

### ISSUE THREAD

**Issue by neelkamath** [kotest/kotest#1473]
## The Problem

Kotest makes us write tests in a class constructor's lambda like this:
```kotlin
class MyTest : FunSpec({
    test("my test case") { /* test case */ }
})
```
It is normal to have hundreds of lines in one of these lambdas. This causes Intellij to constantly [invalidate the cache](https://youtrack.jetbrains.com/issue/KT-13474#focus=streamItem-27-1573280.0-0) which makes Kotest seemingly unusable. It took me several hours before finding and trying the right issue on YouTrack before I could write tests in the IDE (prior to finding this fix, I had to type in a text editor). This is definitely an issue with the lambda because the rest of many people's IDEs work flawlessly (except for this one issue). Even allocating 4 GB of RAM to IntelliJ doesn't help the cache invalidation issue in any noticeable manner.

## Why I Want This

I know this is more of a IntelliJ/Kotlin issue but I saw the same [issue on Spek](https://github.com/spekframework/spek/issues/874)'s repo and think this is something a lot of people run into. Besides, it's not like Kotlin/JetBrains has this readily documented elsewhere because such lambdas are only really used in these modern testing frameworks. Also, I remember seeing Kotest previously document that using infix functions (e.g., `x shouldBe y`) had poorer autocomplete in the editor, so I think this editor-specific documentation fits right in.

## Possible Solution

Most Kotliners use IntelliJ. Therefore, I propose a documentation update stating that lambdas which are over ~100 lines should be moved outside the constructor as shown in the previously linked issue. For example, the sample code above would now look like:
```kotlin
class MyTest : FunSpec(body)

private val body: FunSpec.() -> Unit = {
    test("my test case") { /* test case */ }
}
```

Note that typing a `String` is still as slow as before (every key press is buffered by a few seconds, or dropped if you type too fast). However, every other aspect of code editing is pretty much just as fast as regular. I have created [this YouTrack issue](https://youtrack.jetbrains.com/issue/KT-39278) in regards to the `String` issue. The `String` issue is actually unrelated to the lambda; it seems to be a new bug - any String in any lambda is slow af.

**Comment by sksamuel** [comment]
The ticket says it was fixed in 1.0.5 and I don't notice it myself.
There was some slowness in an earlier version of kotest. What version are
you using?

**Comment by neelkamath** [comment]
Odd. I'm on the latest stables of Kotest, macOS, IntelliJ, Kotlin, and the Kotlin plugin. I saw other YouTrack issues where some people said that disabling the new type inference algorithm fixed their performance issues but it didn't work me. Is there any non-default setting you're using in IntelliJ that might fix this?

**Comment by sksamuel** [comment]
I'm using 2019.3 and 1.3.72 of kotlin and plugin, ubuntu 20.04. I use
either kotest 4.05 or the latest snapshot from master. You could try the
snapshot see if that helps, you shouldn't need to do anything but switch
versions.

**Comment by neelkamath** [comment]
Sadly, the SNAPSHOT didn't help.
I had large lambdas in Kotest class constructors in a project I wrote in 2019. If I remember correctly, there was no issue with the lambdas at that time. _Maybe_ the cache invalidation bug made its way back into IntelliJ 2020.
Considering that the class constructor lambda issue was raised in Spek's repo recently, I think this is a temporary IDE bug; because since only a few days ago, typing `String`s causes my IDE to hang. So I'll close this issue.

**Comment by crazyk2** [comment]
I have the same issue with my tests. And track this [issue](https://youtrack.jetbrains.com/issue/KT-32158)

**Comment by sksamuel** [comment]
Neel do you have a link to the spek issue.

**Comment by neelkamath** [comment]
@sksamuel yes, it's from my original comment: https://github.com/spekframework/spek/issues/874

**Comment by sksamuel** [comment]
I don't use 2020 because it has a bug with mpp projects stopping them being
opened. In general it seems to be a very buggy release.

**Comment by neelkamath** [comment]
I've tried downgrading Kotlin's JVM target from 14 to 8, and then using IntelliJ 2019. Neither worked for me. I'll try to remember to update here if it ever gets resolved :(

**Comment by crazyk2** [comment]
> I don't use 2020 because it has a bug with mpp projects stopping them being opened. In general it seems to be a very buggy release.

I use 
```
Ubuntu 18.04.4 LTS
IntelliJ IDEA 2019.3.5 (Ultimate Edition)
Build #IU-193.7288.26, built on May 6, 2020
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-25-generic
Memory: 4029M
Cores: 8
```

**Comment by neelkamath** [comment]
@crazyk2 the `String` issue has gotten worse for me now, to the point where it's slow even in the `main` source set for functions ~20 lines. To help me better diagnose this, do you mind letting me know if taking the lambda out of the class constructor helps you?

In essence, does writing:
```kotlin
class MyTest : FunSpec(body)

private val body: FunSpec.() -> Unit = {
    test("my test case") { /* test case */ }
}
```
instead of just:
```kotlin
class MyTest : FunSpec({
    test("my test case") { /* test case */ }
})
```
help noticeably for editing code in general?

**Comment by sondr3** [comment]
I'm having the same issue myself right now with IntelliJ and Kotest, autocompletion is extremely slow. I did what @neelkamath suggested and the resulting improvement in responsiveness is very noticeable. I might start considering moving to Junit for testing simply because of the extremely slow responsiveness of the IDE.

**Comment by neelkamath** [comment]
@sondr3 I did: https://dev.to/neelkamath/why-i-migrated-from-kotest-to-junit-2k41

**Comment by sksamuel** [comment]
Is it still slow if you just use an init block @sondr3  ?

```kotlin
class Test : FunSpec() {
  init {
     test("foo") {
     }
   }
}
```

**Comment by sksamuel** [comment]
@neelkamath what do you mean by _Gradle's --tests filter only works for top-level classes_ and _The lack of pretty printing means that you almost always have to debug the test case regardless of whether a more expressive matcher was used_. Some more context would be good.

The rest of your points in that blog post are either gradle/junit limitations or IDE bugs. The idea is to ditch junit platform completely, as the upsides are now less than the downsides. https://github.com/kotest/kotest-gradle-plugin

**Comment by sondr3** [comment]
I'm using the `DescribeSpec` and it was still terribly slow, it's still slow, but fairly reasonable.

**Comment by sksamuel** [comment]
Do you have the kotest plugin installed? If so, try removing it and see if
that makes a difference.

**Comment by neelkamath** [comment]
@sksamuel this is what I mean about Gradle's [`--tests` filter not working](https://github.com/kotest/kotest/issues/1432). Basically, you can filter by class, but not nested function which is important in integration test suites). By _lack of pretty printing_, I'm referring to [this thread](https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1592537729499000).

I'm aware that Kotest's limitations are mostly Gradle, etc. problems, but as an end user the problems still remain. Even if Kotest were to remove those dependencies, I find using the already multi-platform `kotlin.test` package simpler as there are a negligible number of issues with it, and JUnit/Gradle/kotlin.test are pretty standard in the Kotlin/JVM world.

Don't get me wrong, I think Kotest is a great dependency, and I'm open to using its assertion package later on should I have such a use case, but I've found the more conventional approach to be better for a lot of use cases.

**Comment by sksamuel** [comment]
I see your point on comparing different types of data classes. We have nice format now for data classes that are not equal but of the same type. The matchers should be changed in 4.3 to use better type inference to move as much as possible into compile time. I'm looking into that.

The --tests thing is squarely a gradle "bug". --test values are turned into instances of `ClassMethodNameFilter` which expects class names and method names, which is at odds with the design of JUnit 5 platform. These issues have been reported years ago to the gradle team but they're low priority I guess. 

But yes I agree with you, me saying it's a problem with gradle/junit doesn't help the end user. That's why we're working on a new gradle plugin that make the junit5 support redundant (and thus optional). Plus, with the new kotest intellij plugin, and as Kotest becomes more multiplatform aware, the junit support is less useful than it was.

One area I think you might like, is that the Kotest JS test experience I think is better than the built in kotlin.test experience. Most assertions/matchers are cross platform, property testing is js/jvm and the framework support is nice, with the coroutine => js promise conversion.

**Comment by sksamuel** [comment]
I've been playing with the --tests thing again and there's no way I can see to get it to work for nested test names. We don't get access to the "string" that is passed as the arg. Gradle just provides a filter which doesn't expose the string that was used and then tries to match on method names. 

I think speed issues with nested lambdas has gone away in Kotlin 1.4.21 and is even better in 1.4.30 RC.

I will close this issue now since a) cannot be done and b) seems good now. Please re-open this issue if anyone is still seeing slowness with kotlin.
