### ISSUE TITLE
IsolationMode default encourages bugs

### ISSUE THREAD

**Issue by DanyalBurke** [kotest/kotest#1525]
The Default IsolationMode is SingleInstance but this is problematic because it means that by default, mocks and other items are shared between tests and tests are not as isolated as they could be.

For example, verifications from one test might be satisfied by interactions from another test.

This leads to bugs, and on an anecdotal level, having a bug for which the fix is setting the IsolationMode to InstancePerTest or InstancePerLeaf is a regular occurrence.

**Comment by sksamuel** [comment]
It's like this because the inspiration for Kotest was ScalaTest, not JUnit.

So if you come from JUnit land you might think it's surprising. If it was the other way, then people coming from other frameworks might find it surprising.

Either way, we can't change it now, otherwise we run the risk of breaking everyone's tests.

**Comment by DanyalBurke** [comment]
Thanks, I acknowledge that the surprise is largely because of prior experience with the JUnit style.

However, JUnit was once not instance per test either and switched to the instance per test design because it was considered superior - since we're counting on tests to be accurate and bug free, anything that helps towards that goal has got to be a win.

I'm happy for the issue to be closed if we agree with the 'surprise due to prior background' conclusion.

**Comment by sksamuel** [comment]
It probably was a mistake to do it the scalatest way in retrospect.
If there was a way to switch over without breaking anyone's code, I think we'd probably do it.

**Comment by reevn** [comment]
I disagree that `SingleInstance` as a default was a mistake. `SingleInstance` by design is a much more performant way to run tests and encourages test writers to express exactly what they want to happen at every point in a test file. All the heavy lifting of creating initial mocks/dummys only is done once, and callbacks are used to clear them before each test execution.

An entire test code base written in the `SingleInstance` style will run **much** faster than the JUnit standard way.

As someone who also came from other languages and testing frameworks (`Jest`/`Jasmine`), it was always very weird to me how this is the standard behaviour in JUnit. I don't think most people without prior knowledge of test frameworks would expect their test class to be created anew before every single test execution, especially when that is the exact use-case for features like `beforeEach`/`beforeAll` etc. in most testing frameworks.

I have to say JUnit just seems to be the odd one out here.

**Comment by sksamuel** [comment]
@Reevn nice to see someone else likes SingleInstance as the default :+1: 

I have updated the docs to explain why this is the default.
