### ISSUE TITLE
NoSuchFileException when using kotest-extensions-junitxml with Gradle

### ISSUE THREAD

**Issue by mnonnenmacher** [kotest/kotest#1581]
I am trying to use `kotest-extensions-junitxml` to get a flattened JUnit report in a Gradle project (related to #999), but every test class fails with a `NoSuchFileException`, because it is looking for the XML file in the `target` directory, instead of `build/test-results/test/` where Gradle puts the file.

This behavior is currently hardcoded: https://github.com/kotest/kotest/blob/056c8b58cbfe601039d5a671abe0bd381b6e19d3/kotest-extensions/kotest-extensions-junitxml/src/jvmMain/kotlin/io/kotest/extensions/junitxml/JunitXmlListener.kt#L90

I have only added the dependency to `io.kotest:kotest-extensions-junitxml:4.1.2` [1], is there anything else I need to do to make it work?

You can see the error here: https://travis-ci.com/github/oss-review-toolkit/ort/builds/176483622#L1023

[1] https://github.com/oss-review-toolkit/ort/pull/2872/files

**Comment by sksamuel** [comment]
Will be fixed for 4.2.0

**Comment by sksamuel** [comment]
Fixed in master. You will need to specify the build dir when you setup the tests in gradle like this: https://github.com/kotest/kotest/blob/master/kotest-tests/kotest-tests-junitxml/build.gradle.kts#L47

Additionally, you will need to add the JUnitXmlReporter as a listener manually, rather than using AutoScan, similar to this: https://github.com/kotest/kotest/blob/master/kotest-tests/kotest-tests-junitxml/src/jvmTest/kotlin/com/sksamuel/kotest/ProjectConfig.kt

**Comment by mnonnenmacher** [comment]
Thanks @sksamuel, that's great news. I have tried 4.2.0-RC1 and it works!
