### ISSUE TITLE
Variation of clue / asClue to accept lazy

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1766]
**Please describe the feature you'd like to see including any solutions in mind if you have any**

**Comment by jschneidereit** [comment]
I wouldn't mind taking a stab at it. My first thought was to add something like `asLazyClue` that has a catch instead/in addition to a finally to only push the value of the lazy if something was caught. Though this seems like you'd need to intercept whatever is added to the errorCollector as a result of executing block.

```kotlin
inline fun <T : Any, R> Lazy<T>.asLazyClue(block: (Lazy<T>) -> R): R {
   try {
      return block(this)
   } catch (ex: Throwable) {
      errorCollector.pushClue(this.value)
      throw ex
   }
}
```

Something like that, but I'm new to this project so that seems like I'm missing something, like the clue would come after an error in the report.

**Comment by sksamuel** [comment]
I was thinking we could change the ErrorCollector to store clues as functions () -> String and so the lazy impl could be something like:

```kotlin
inline fun <R> withClue(clue: Lazy<Any>, thunk: () -> R): R {
   try {
      errorCollector.pushClue({ clue.value.toString() })
      return thunk()
   } finally {
      errorCollector.popClue()
   }
}
```

I'm not sure it makes sense to have asClue accept a lazy, because you'd be immediately unlazy-ing it to run the test, so what's the point.

It makes sense with `withClue` where you might never need the clue.

If you go with my idea, you would need to re-jig the existing functions to support the ErrorCollector change.

**Comment by jschneidereit** [comment]
Oh of course, shouldn't have written that at midnight 😂  you're right about `withClue` for sure. I'll take a stab at it today!
