### ISSUE TITLE
Spec.timeout is of type `Long?` not `Duration`

### ISSUE THREAD

**Issue by Woodz** [kotest/kotest#1808]
**Which version of Kotest are you using**
4.3.0

As per https://kotest.io/timeout/, `Spec Level Timeouts`, it shows that the datatype of `Spec.timeout` is `Duration`:
```
class TimeoutTest : DescribeSpec({

   timeout = 1250.milliseconds

   describe("I will timeout in 1250 millis") {
      it("And so will I") { }
      it("But I'm a little faster").config(timeout = 500.milliseconds) { }
   }

})
```

yet this is not correct:
![image](https://user-images.githubusercontent.com/966157/97391956-71dc3380-191b-11eb-96fa-53ace524df34.png)
https://github.com/kotest/kotest/blob/62e8a3d4607335b84d1fee3a24455b2cc89b86d9/kotest-framework/kotest-framework-api/src/commonMain/kotlin/io/kotest/core/spec/Spec.kt#L57 clearly shows the datatype is `Long?` 

Given that the documentation and the other levels of timeout config (`Test Level Timeouts` and `Project Config`) are of type `Duration`, it would seem sensible to change `Spec.timeout` and `invocationTimeout` to `Duration?`

**Comment by sksamuel** [comment]
The reason is that using duration was a bad decision. It was experimental and back then I thought experimental would not be quite as flakey as it is. My mistake. When 1.4.0 came out, durations were causing some backwards compatibility issues, so as part of 4.2.0 we removed all internal usages of durations. The timeout values on tests are part of the public API so could not change. The spec level values are new, and so it was safer to stick with longs. A touch inconsistent yes, but safer.

Once Durations are no longer experimental (who knows when?) then everything in Kotest will be updated to support them.

**Comment by sksamuel** [comment]
Closing this - durations will be used once kotlin 1.5 is released (if they are no longer experimental by then).
