### ISSUE TITLE
Kotest 4.3.0 has classpath issues with Coroutines 1.4.0

### ISSUE THREAD

**Issue by yonatang** [kotest/kotest#1816]
When kotest is on the classpath **after** `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.0`, `NoClassDefFound` will be thrown on different cases.
When kotest is on teh classpath **before** `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.0`, the same cases will work.
When kotest is on the classpath before or after `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9`, it will work.

Example can be shown here: https://github.com/yonatang/kotest-coroutine-issue. If you'll `mvn clean install` it as is, `NoClassDefFound kotlin/KotlinNothingValueException` will fail the test. If you'll edit the pom file, and move the kotest above the coroutines dependency, it will pass. If you'll downgrade to coroutines 1.3.9 it will pass.

**Comment by frikit** [comment]
If you set kotlin version 1.4.10 it works, and it is because kotlin 1.4.x and coroutines 1.4.x have some breaking changes compare to previous 1.3.x version.

In my opinion testing lib should not fix the core libraries incompatibilities what do you think @sksamuel ?

I am new in the community just try to help the project :)

**Comment by sksamuel** [comment]
I agree with @frikit, if coroutines 1.4.0 has an incompatibility with 1.4, then I don't think there's much we can do.
