### ISSUE TITLE
Better tags for spec level includes/excludes

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#1820]
The current @Tags on a spec is powerful but can be confusing. A spec annotated with @Tags("Foo") will not necessarily be excluded if you run with kotest.tags=Bar because root level tests may be annotated with Bar and so it must instantiate the spec to check. Only if a tag is explicitly excluded does the @Tags on a spec help.

This ticket is to:
* Add a new annotation (name whatever, say @Tagged) which, when an include is set, is required, and when an exclude is set, must not be present, for that spec to be instantiated. 
* deprecate @Tags.

**Comment by kopper** [comment]
To give you some context let me describe our use-case first. As many other projects we have unit and integration tests. We would like to be able to run only one set of them. Right now we are using naming convention *Test for uni tests and *IT for integration and maven surefire plugin to run unit tests while maven failsafe plugin to run integration tests. I expect us to define more test types in the future and classify some as "slow" to avoid running them too frequently.

In order to save time/CPU we'd like to avoid instantiating specs that are not of the type that was requested to run. I understand that in order to determine all tags associated with the test we need to instantiate the spec.

What would work in our case is to have distinction between test type and test tag, for example:

```
@TestType("UnitTest")
class MyTest : FunSpec({
  tags(SlowTest, FlakyTest)
}
```

and then `-Dkotest.type=IntegrationTest` wouldn't even instantiate the spec.

**Comment by sksamuel** [comment]
Your use case is the perfect example of what I was trying to convey.

Although rather than introduce two types of tags/things, I think just having a different annotation may be easier, because then it expands out to any use case. For example @jschneidereit uses a different tag per team.

```kotlin
@RequiresTag(UnitTest) // tag must be present to be instantiated
class MyTest1 : FunSpec({
  test("a").config(tag = FlakyTest) { }
  test("b").config(tag = SlowTest) { }
}

@Tags(FooTag) // a tag that is simply added to the other tags of the tests
class MyTest2 : FunSpec({
  test("c").config(tag = FlakyTest) { }
  test("d").config(tag = SlowTest) { }
}
```

MyTest1 will now only be instantiated when kotest.tags explicitly includes UnitTest.

So under the following behaviors.

kotest.tags=UnitTest => a,b (but MyTest2 is instantiated to search inside)
kotest.tags=UnitTest & FlakyTest => a (but MyTest2 is instantiated to search inside)
kotest.tags=FlakyTest => a, c
kotest.tags not specified = a, b, c, d
kotest.tags=!UnitTest=c, d (MyTest1 never instantiated)
kotest.tags=!FlakeyTest = b, d
kotest.tags=FooTag = c, d (MyTest1 never instantiated)

The name of this annotation could be something other than RequiresTag of course. And Tags _could_ be deprecated and replaced with another tag that is more clear, such as InheritTags or TestTags or something.

^^ @SergKhram This is what you are wanting from https://github.com/kotest/kotest/pull/1823

**Comment by SergKhram** [comment]
@sksamuel 
kotest.tags=UnitTest => a,b (but MyTest2 is instantiated to search inside)
kotest.tags=FlakyTest => a, c

How it can work? If you write ```@RequiresTag(UnitTest) // tag must be present to be instantiated```
I think it should be only c in case kotest.tags=FlakyTest (because we need to instantiate the spec to know what tags inside - in cases)
