### ISSUE TITLE
Spring test lifecycle callbacks do not work with constructor injection

### ISSUE THREAD

**Issue by StragaSevera** [kotest/kotest#1980]
I have the problem that is described here: https://github.com/kotest/kotest/issues/950 . Because that issue is closed, I'm opening a new one.
I made a simple example that reproduces the `No transactional EntityManager found` problem: https://github.com/StragaSevera/kotest-spring .  I'm using the 4.3.2 version of Kotest, using only one layer of nesting, etc, but it still does not work.

**Comment by sksamuel** [comment]
Thank you for making the repo, that is a big help.

The problem seems to be that the constructor based injection doesn't run the "before test method" callbacks (because it's only constructing the class) so some setup methods never get called (such as setting up the test entity manager).

This works:

```kotlin
class ProjectConfig: AbstractProjectConfig() {
    override fun listeners(): List<Listener> = listOf(SpringListener)
    override val isolationMode = IsolationMode.InstancePerLeaf
}

@DataJpaTest
@Transactional
class RepositoriesTests : FunSpec() {

   @Autowired
   lateinit var entityManager: TestEntityManager

   @Autowired
   lateinit var userRepository: UserRepository

   init {
      test("findByFirstName returns User") {
         val user = User("Ivan", "Petroff")
         entityManager.persist(user)
         entityManager.flush()

         userRepository.findByFirstName("Ivan") shouldBe user
      }
   }
}
```

I will figure out a way to make the constructor injection work as well.

**Comment by StragaSevera** [comment]
Thank you, if I setup tests like you show, they work =-)

**Comment by sksamuel** [comment]
Closing this as constructor injection works as well, just need the listener as in the example.
