### ISSUE TITLE
Probabilistically use edge cases with random data instead of a cartesian product of all edge cases

### ISSUE THREAD

**Issue by renpillay** [kotest/kotest#2112]
Current status: Given 2 arbs with 5 edge cases each, a test that uses these two arbs would require 25 (5*5) iterations before going into testing random values. This scales poorly with a large amount of arbs, or when combining arbs. For example - if we instead had 4 of these arbs, we'd need a minimum of 625 iterations. 6 of these arbs = 15,000. 8 = almost 400,000.

This makes using complex objects or a objects with a large amount of edgecases infeasible. A potential solution to this would be to probabilistically pull in edgecases, rather than exhaustively. For example - whenever generating a value, pull out an edgecase 10% of the time and a random value 90% of the time.

This would achieve the task of checking the more problematic values more frequently, and testing combinations of these edge cases more frequently, without having the iteration count for tests skyrocket.

Additional context on the kotlinlang slack with @sksamuel and @myuwono : https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1613715625006600

**Comment by sksamuel** [comment]
So we have two methods currently:

```
edgecases(rs: RandomSource)
sample(rs: RandomSource)
```

Do we make edge cases return a single value (randomized, but within the "edge case constraints"), and the framework then picks from either an edge or a sample (weighted towards samples, customizable) or do we stick with a list.

Do edge cases still need the random parameter anymore, because now it's feasible to have larger edge cases lists (before the list was kept small to try and avoid the Cartesian explosion).

Finally, @myuwono how would this affect your recent work on bind.

**Comment by myuwono** [comment]
> Do edge cases still need the random parameter anymore

We still do, because even if we transition to probabilistic edgecases, bind / flatMap will still suffer the same bug because of the product with empty list. So that work still have to be done, but the way we solve that will have to depend on this now.

On type, you're right i've been thinking along the same lines regarding types. in 4.5 what we can do is to have the following instead
```kotlin
edgecases(rs: RandomSource): A
sample(rs: RandomSource): Sample<A>
```

we need to have something like that if we were to address #2112 and #2095. Would this also mean maybe we should name it singular `edgecase(rs)` instead of the plural version? 

I also have a question about probability ratio / customizability. As in, do we customize this on the `Arb.bind` level as well? or the config during generation is sufficient? The reason i asked is because to satisfy the behaviour described in the slack thread `Arb.bind` needs to independently able to combine the random edgecases from multiple arbs. 

Below is the result if we pursue Arb.bind-level configuration + generation level edgecases probability
```kotlin
val arbA = Arb.string(1).withEdgecases(...)
val arbB = Arb.string(1).withEdgecases(...)
val arbC = ...
// determinism factor dictates how deterministic is the edgecases generation in bind will be. 
//   - 90% of the time edgecases(rs) will return edgecases, 
//   - 10% of the time it will return sample
val arb = Arb.bind(
    edgecasesDeterminism=0.9, 
    arbA, 
    arbB, 
    arbC.withEdgecases(emptyList())
) { a, b, c -> fn(a,b,c))

val rs = RandomSource.seeded(1234L)
val seq = generateSequence { arb.edgecases(rs) }
println(seq.take(5))
// rn = random, ec = edgecases
a_ec, b_ec, c_rn 
a_rn, b_ec, c_rn
a_ec, b_rn, c_rn 
a_ec, b_ec, c_rn 
a_ec, b_ec, c_rn 

val sampleAndEdges = arb.generate(rs, edgecasesProbability=0.1) // probability to call edgecases(rs) or sample(rs)
// rn = random, ec = edgecases
a_rn, b_ec, c_rn // edgecases
a_rn, b_rn, c_rn // sample
a_ec, b_ec, c_rn // edgecases
a_rn, b_rn, c_rn // sample
a_rn, b_rn, c_rn // sample
a_ec, b_ec, c_rn // edgecases
```

Below is the result if we pursue configuration only at generation time. This is effectively the same with hardcoding edgecases determinism to 100%. Notice how we now have edgecases containing 100% edgecases only.
```kotlin
val arb = Arb.bind(arbA, arbB, arbC.withEdgecases(emptyList())) { a, b, c -> fn(a,b,c))

val rs = RandomSource.seeded(1234L)
val seq = generateSequence { arb.edgecases(rs) }
println(seq.take(5))
// rn = random, ec = edgecases
a_ec, b_ec, c_rn 
a_ec, b_ec, c_rn
a_ec, b_ec, c_rn 
a_ec, b_ec, c_rn 
a_ec, b_ec, c_rn

val sampleAndEdges = arb.generate(rs, edgecasesProbability=0.1)
// rn = random, ec = edgecases
a_ec, b_ec, c_rn // edgecase
a_rn, b_rn, c_rn // sample 
a_rn, b_rn, c_rn // sample
a_ec, b_ec, c_rn // edgecase 
a_rn, b_rn, c_rn // sample
a_ec, b_ec, c_rn // edgecase
a_rn, b_rn, c_rn // sample
```

i'd probably lean towards having another configuration at the arb.bind level with a sane default determinism like 90%.

**Comment by sksamuel** [comment]
I tend to favour the configuration as a parameter to Arb.bind.

What I was asking about with "do we need it" was this - since a bind accepts k gens, and since the values generated by each of those gens already includes some degree of edgecaseness, does bind need to provide any edge cases at all? In other words, the edgecaseness of bind is implicitly supplied via the values provided by the underlying generators. This means you would not necessarily get 100% edgecases from bind, but that's what this whole ticket is about anyway right ?

**Comment by myuwono** [comment]
Nice yeah, i do prefer the bind level conf as well.

I see, indeed you can get the random edge+sample by calling Gen.generate(rs) in bind/flatmap's sample(rs) however I think we should not. My suggestion is to not conflate the two. I would still vouch for introducing `edgecase(rs)` or `generateEdge(rs)` mainly because of the following:

One that i was trying to avoid is implicitly dirtying `sample(rs)` with edgecases from the underlying arbs. That can really throw some curveball to the expectations of some devs. The problem is because they can't really remove or modify the edgecases after bind because it's baked in `sample(rs)` now. At the worst case it'll give them the wrong incentives to remove all edges from all arbs, and that would not be good.

Similarly with flatMap, we can pursue the proposition of incorporating edges as part of sample but that has the same drawbacks as above. On the other hand, if we were to treat edgecases separately without `generateEdge(rs)` we can't. We don't have access to rs in edgecases, as soon as we are flatMapping an underlying arb without an edgecase, then the final arb would be guaranteed without edgecases.

**Comment by myuwono** [comment]
I'll raise a sample PR some time this week to illustrate what i mean. The positive is that i imagine everything becomes much simpler with probabilistic edges.

**Comment by sksamuel** [comment]
Ok that all sounds good.

**Comment by sksamuel** [comment]
> I see, indeed you can get the random edge+sample by calling Gen.generate(rs) in bind/flatmap's sample(rs) however I think we should not. My suggestion is to not conflate the two. I would still vouch for introducing `edgecase(rs)` or `generateEdge(rs)` mainly because of the following:
> 
> One that i was trying to avoid is implicitly dirtying `sample(rs)` with edgecases from the underlying arbs. That can really throw some curveball to the expectations of some devs. The problem is because they can't really remove or modify the edgecases after bind because it's baked in `sample(rs)` now. At the worst case it'll give them the wrong incentives to remove all edges from all arbs, and that would not be good.

This is a good reason not to just use generate instead bind like I was suggesting.

I think the implementation here can be simplified a bit, and I want to remove options in the public API for reasons I discussed previously. Let me merge this in and create another PR that proposes some further modifications.
