### ISSUE TITLE
Data tests fail silently on Android Studio preview

### ISSUE THREAD

**Issue by 1sao** [kotest/kotest#2331]
I am using the latest version of Kotest in my Android project. 
The problem is that usage of kotest-framework-datatest is impossible without kotlin-reflect, but there's no info about it in the docs, and more than that: when kotlin-reflect is missing, datatests are just skipped without any visible error in case you're running all tests. If you're running a specific class, datatests are skipped as well. Only when you run a specific datatest you're able to see the error. It took me quite a while to realize.

**Comment by 1sao** [comment]
It turned out that the problem is way bigger. Any errors in data test are getting swallowed if not running one test specifically. Also this problem persists if using `forAll(...)` or even ordinary `listOf(...).forEach {...}`. 
This practically makes any data test unusable, so it makes me think there's something wrong with my setup. But it is reproduced even in a fresh project with no other dependencies. I re-read the documentation to make sure I've done everything that was needed, but still no luck. I'm at a loss.

**Comment by 1sao** [comment]
Here's the link to the sample project: https://github.com/IhorPakharenko/Kotest-Please-Fix/blob/b560148b72f7319d0f60aae8d0664bf0e30aed2a/app/src/test/java/com/example/kotestpleasefix/ExampleUnitTest.kt

**Comment by sksamuel** [comment]
So to clarify, if I run ExampleUnitTest then you will see no errors ?
And are you running from the IDE or via gradle ?

**Comment by sksamuel** [comment]
This is what I get:

![image](https://user-images.githubusercontent.com/743706/123788278-70477e80-d8a1-11eb-9add-0be01728efbd.png)

A couple of things. Firstly, I couldn't get your project to work properly but I assume that's some android thing (app folder?). I copied the unit test into another project to run it.

Secondly, the forAll is the "old" datatest stuff that will be deprecated in 5.0 once the new stuff has been tested out. So I wouldn't mix and match datatest approaches.

Thirdly, when running from the IDE you can run either via gradle or via intellij. When the former, the errors don't seem to come into the console properly (but it does fail the build and tell you there were test errors).

![image](https://user-images.githubusercontent.com/743706/123788568-c87e8080-d8a1-11eb-97db-62cd7e327b39.png)

You can try switching those settings (if they exist in android studio).

Lastly, FreeSpec is a confusing one. The minus symbol creates a parent test. When you use that with the new data test stuff, it's fine, because the new stuff works out if it's in a parent test / leaf test. The older forAll doesn't, it just literally makes a loop. 

If you are still having issues I would remove the forAll with row, and then if still issues, try FunSpec just to see if that works.

**Comment by 1sao** [comment]
Thank you for the response!

Firstly, I suppose the problem is somewhere in Android Studio (or more like in how I am using it), if the tests are running as expected on your end without Android Studio.

Secondly, I mixed up withData and forAll just for this test. The problem persists if I use only one approach in the file, and also if there's a single test in the file. Anyway, I split them into two classes just to be sure.

Thirdly, no such options exist in Android Studio, sadly.

Lastly, I tried data tests with multiple approaches, including FunSpec, the result is the same every time. Again, just to be sure, I changed FreeSpec to FunSpec.

Here's what I get when I run all tests:
![image](https://user-images.githubusercontent.com/22911624/123906605-2a5fe880-d97d-11eb-8d67-bda2a0644fe6.png)
The same picture when I run test class (the one that extends FreeSpec/FunSpec).
When I run one single test, it works as expected:
![image](https://user-images.githubusercontent.com/22911624/123906786-7a3eaf80-d97d-11eb-982a-ca07abbeac1c.png)

**!!! The (kinda) solution is below !!!**
Tests are working fine out of the box on [stable Android Studio](https://developer.android.com/studio), but fail on [preview release of Android Studio](https://developer.android.com/studio/preview). Sadly there's no way I can get back to stable Studio, as my project uses Jetpack Compose, which is available only on preview as of now. There are still two questions left:
1. Maybe someone should add it to the Kotest docs? It would save a lot of time for someone who uses preview like me. 
2. Who is supposed to fix this issue? Should I create the issue for Jetbrains as well?

**Comment by 1sao** [comment]
Can confirm the issue still persists on Android Studio Arctic Fox 2020.3.1 Beta 5 (currently the latest version)

**Comment by iainism** [comment]
Could it be to do with this:  https://developer.android.com/studio/releases#test-configurations ?

I'm just looking at the Arctic Fox Release Notes now as it has gone stable (and STW after reading that Gradle is default, in case of issues in testing with Kotest brought me straight here), however breaking all my tests will upset me, so I'm going to investigate further before hitting the button!

**Comment by sksamuel** [comment]
Does it ignore failing tests or is it not actually running the tests ?

**Comment by sksamuel** [comment]
Did anyone make progress on this ?

**Comment by sangrambankar** [comment]
the test cases are passing but the build's are failing similar to this 3 year old issue when gradle was upgrade to 4.7 i guess. https://github.com/gradle/gradle/issues/5273

I installed the new Android Studio Fox since i have to add support to jetpack compose in my project, i have to upgrade my gradle to 7.0.2. 


The test case do pass, but the build fails with the following expection

Thats's the exception.
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:testDebugUnitTest'.
> Received a completed event for test with unknown id '24.4'. Registered test ids: '[24.1, :app:testDebugUnitTest, 24.2]'
```
# Further Findings
any test cases who has a nested hierarchy, i.e in my case, any test class extending `DescribeSpec` the test case passes but the build fails.
And if any class which extends i.e `StringSpec` the test cases and build both are passing. 

I'm not sure, if it's gradle or kotest issue, just posting my experience here so that it might help someone else.


P.S. All my testcases and  builds use to pass on gradle 6.2 and lower
@sksamuel @IhorPakharenko

**Comment by sksamuel** [comment]
@sangrambankar can you try with Kotest 5.0 and a gradle 7+ build ?
