### ISSUE TITLE
concurrentTests not being respected during ConcurrentTestLauncher [kotest 4.6.3]

### ISSUE THREAD

**Issue by williamokano** [kotest/kotest#2623]
During some experimenting with kotest, I was playing around with the `parallelism`, `concurrentTests` and `concurrentSpecs`.

When setting the `concurrentTests` to something higher than 1, it just burst and execute all the tests all at once, even if I have a delay (which could be due to being suspended) or if I have hacky stuff like doing nothing for X amount of seconds (to ensure no suspension points were available) and it still burst the number of tests being triggered all at once.

I noticed that it relies on `kotlinx.coroutines.sync.Semaphore` and on `Semaphore.withPermit`.

Also, what I should expect if I have 4 Specs with 12 tests each and I set the values to `concurrentTests = 3` and `concurrentSpecs = 2`?

As far as I understood the code, 1 coroutine should be launched for each spec and 3 coroutines should be launched for each test, totaling 6 concurrent tests running at once.

If that's the case, seems that `concurrentTest` is not super useful, since I can't have fine tunning on how many tests I'm running all at once. I don't whether this makes sense or not to be honest, but if I set the `concurrentTests` for 10, I understand that I shouldn't have more than 10 tests running at the same time globally.

One solution could be this also be configurable, like `IsolationMode`, so I could configure `concurrentTests` per Spec or Globally.

Kotest version: 4.6.3
Java version: Adopt 10.0.11-hs-adpt
Kotlin version: 1.5.31

**Comment by williamokano** [comment]
I believe I have found the problem. On version `4.6.3`, `ConcurrentTestLauncher.launch` seems to be using the semaphore in a wrong way.

Instead of using `semaphore.withPermit` inside the launched coroutine, it is using outside of the coroutine, on the for loop. As coroutines launched by `launch` as fire-and-forget, I believe that the `permit` is being acquired and released even if the coroutines didn't have yet executed.

The implementation on [DefaultSpecLauncher.concurrent](https://github.com/kotest/kotest/blob/v4.6.3/kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/launchers/DefaultSpecLauncher.kt#L65) does differently, it loop through the specs, launch the coroutines and use the semaphore inside the launched coroutine, as [ConcurrentTestLauncher.launch](https://github.com/kotest/kotest/blob/v4.6.3/kotest-framework/kotest-framework-engine/src/jvmMain/kotlin/io/kotest/engine/launchers/ConcurrentTestLauncher.kt#L26) uses the semaphore before launching the child coroutine.

**DefaultSpecLauncher.concurrent** example (with ommited parts):
```kotlin
      coroutineScope {
         specs.forEach { spec ->
            // ...
            launch(dispatcher) {
               semaphore.withPermit {
                  // ...
                  executor.execute(spec)
               }
            }.invokeOnCompletion { factory.complete(spec) }
         }
      }
```
**ConcurrentTestLauncher.launch** (with ommited parts) example:
```kotlin
      coroutineScope {
         tests.forEach { test ->
            semaphore.withPermit {
               // ...
               launch(dispatcher) {
                  // ...
                  run(test)
                  // ...
               }.invokeOnCompletion {
                  // ...
               }
            }
         }
      }
```

I would open a PR to fix this, but I took a quick look and it seems that on the 5.0.0 the structure changed quite a bit, and I still don't know whether the problem persists.

Should I create a PR for `4.6.3` branch in order to fix this issue or should I leave it as it is?

**Comment by sksamuel** [comment]
I think there's a coroutine scope in the loop too to stop that happening.
I'll check more and give a full reply to your posts tomorrow night when I'm
back from vacation.

**Comment by williamokano** [comment]
Hi @sksamuel, thanks for replying back.

I updated the second comment with a few pieces of evidence and links that might help you find it faster. I can provide a demo project in which I was using to play around with these configurations if it helps.

I'll write some tests and a potential fix for it and I'll post a PR if it's not a problem.

Ain't an expert in Kotlin nor Coroutines, so I don't fully understand what is the purpose of `coroutineScope` except that if the children fail, the parent will fail as well and cancel the other ones.

Enjoy your vacation and reply.

**Edit**: 

I was just checking the new version `5.0.0.M3` and I can see that this issue was solved as it can be seen [here on ConcurrentTestScheduler.schedule#27](https://github.com/kotest/kotest/blob/master/kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/test/scheduler/ConcurrentTestScheduler.kt#L27).

**Comment by sksamuel** [comment]
So bugs aside, this is the current thinking of the concurrency modes.

`concurrentSpecs` allows you to configure how many specs run at a time. If you set it to 1, then all specs will be isolated.

`concurrentTests` allows you to configure how many tests are launched at the same time inside a particular spec. 1 means all tests are isolated.

What you can't do, as you pointed out, is set how many tests should be running at once over a collection of specs. I guess that could be added. 

With coroutines, it's possible to have millions launched at the same time, so the idea is that you probably want to isolate a spec (shared resources across specs) or isolate inside a spec (all tests sharing a resource the spec is using). That's why the settings are there.

Happy to discuss ideas to improve this.

**Comment by williamokano-dh** [comment]
Hey @sksamuel , the idea behind my "global back-pressure control" or any related name is that at our company, we decided to use kotest as framework for end-2-end testing, and although launching several coroutines are cheap, the work they done, sometimes, it's not.

In our case, we have several tests using selenium and/or rest assured for testing the api's. Using selenium on some tests is a must because it's required for a few payment service providers in order to generate card tokens.

When we spawn all the tests at once, they tend to get slower since the staging test can't handle well that many requests and it becomes flaky-er, so some kind of back-pressure, or concurrency control, would be appreciate.

Since several tests are grouped by Specs, just using Specs as some kind of control would be ok, but we have way more tests than we have Specs, so the concurrency wouldn't be that great.

As for the global concurrency control, we actually don't need that level of fine-graining control, just thought that would be a nice addition to have, but that probably implies that we would need a shared semaphore of some kind.

**Comment by williamokano** [comment]
Hey @sksamuel , the idea behind my "global back-pressure control" or any related name is that at our company, we decided to use kotest as framework for end-2-end testing, and although launching several coroutines are cheap, the work they done, sometimes, it's not.

In our case, we have several tests using selenium and/or rest assured for testing the api's. Using selenium on some tests is a must because it's required for a few payment service providers in order to generate card tokens.

When we spawn all the tests at once, they tend to get slower since the staging test can't handle well that many requests and it becomes flaky-er, so some kind of back-pressure, or concurrency control, would be appreciate.

Since several tests are grouped by Specs, just using Specs as some kind of control would be ok, but we have way more tests than we have Specs, so the concurrency wouldn't be that great.

As for the global concurrency control, we actually don't need that level of fine-graining control, just thought that would be a nice addition to have, but that probably implies that we would need a shared semaphore of some kind.

**Comment by sksamuel** [comment]
So internally there's this thing called the `TestScheduler` which is responsible for determining when to create a test's coroutine. And the `TestSuiteScheduler` does the same for specs. I wonder if we could just combine these and make it possible to plug your own in so you can do what you want. And it would be possible to have a built in option for global concurrency like you want I think.

I have to think how this plays with `CoroutineDispatcherFactory` which is the thing that determines which dispatcher is used, and that's important for thread affinity in tests.

**Comment by sksamuel** [comment]
Have you had any further thoughts on this ?

**Comment by williamokano-dh** [comment]
Hi @sksamuel , sorry for not answering after that.

Regarding the issue, since it's fixed on the newest version, I'll just wait for the release candidate/m-releases phases finish to use the stable version of it.

As for the global concurrency control, I don't think it's needed now for me, it was just a thought I had once I was investigating an issue within our test suite, so I didn't had time to play around or even think a lot about it.

As for your ideia of extensibility of the `TestScheduler`, maybe we could work on that in the future, in not very versed on testing to be honest, but I would love to work on that feature if possible, but at the moment I don't have "capacity".

**Comment by sksamuel** [comment]
Now that 5.0 is out and you're happy with the current state, I will close this.
