### ISSUE TITLE
Assertion shouldBe succeeds even when equals() always returns false

### ISSUE THREAD

**Issue by klozovin** [kotest/kotest#2803]
Here's a simple class that implements a `Set` interface and always returns `false` from its `equals()` method. That should mean that every `shouldBe` assertion fails, right?

In my case, using kotest 5.1.0, first two tests succeed, and the last one fails - it seems kotest is doing something else instead of using the `equals()` method.

Is this a bug, or just unexpected behavior? If so, is there an assertion that always uses the `equals()` method?

```
class ArraySet(vararg items: String) : Set<String> {

    private val items: Array<String> = items.distinct().toTypedArray()

    override val size get() = items.size
    override fun iterator() = items.iterator()
    override fun contains(element: String) = items.contains(element)
    override fun containsAll(elements: Collection<String>) = items.toList().containsAll(elements)
    override fun isEmpty() = items.isEmpty()

    override fun equals(other: Any?): Boolean = false

    override fun hashCode(): Int {
        return items.sumOf { it.hashCode() }
    }
}

class ArraySetTest : FunSpec({
    val o1 = ArraySet("foo", "bar")
    val o2 = ArraySet("bar", "foo")
    val o3 = ArraySet("foo", "bar")
    val o4 = ArraySet("foo, bar, baz")

    test("1. equal up to permutation") {
        o1 shouldBe o2
    }
    test("2. completely equal") {
        o1 shouldBe o3
    }
    test("3. different elements") {
        o1 shouldBe o4
    }
})
```

**Comment by inquiribus** [comment]
```
shouldBe
```
does not test the custom `equals()` method, If `shouldBe` were to be implemented in terms of the `equals()` method, the outcome would be fragile since by default (https://kotlinlang.org/docs/equality.html)  `equals()` may result in address equality and the default may or may not be overridden, To test the custom `equals()` method a possible test is, rather,
```
test("3. different elements") {
        o1.equals(o4) shouldBe false
}
```

**Comment by sksamuel** [comment]
I think shouldBe should (and does) use equals except where we override it for special behavior - like we are doing for sets for example.

This example is failing because I think we are using the iterator methods of set, and thus not the equals behavior.
We should document all the special cases for shouldBe.
And after that I can add lint rules to the kotest plugin to warn you.

**Comment by klozovin** [comment]
Thanks both of you for the explanation, it makes sense. For now, I've used the `(a == b).shouldBe true` form to check for `equals()` equality.

The docs on the `shouldBe` could be a little bit more specific, at the moment it says "...to assert that a variable has an expected value, we can use the shouldBe function". At least mentioning that it does something special for Iterators (and other interfaces) should be enough.

Maybe an `shouldEqual` assertion that explicitly tests for `equals()` equality could be useful?

**Comment by LeoColman** [comment]
There is the EqualityMatcher already, I think we're just missing the infix functions

kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/eq/DefaultEq.kt:14

This is the default equality matcher, it uses `==`
