### ISSUE TITLE
kotest.io documentations list non-existing assertions

### ISSUE THREAD

**Issue by zyxist** [kotest/kotest#2908]
Hello, I noticed that [kotest.io website](https://kotest.io/docs/assertions/core-matchers.html) shows a non-existing assertion:

iterable.shouldMatchEach(assertions)

The doc version in the repository, on the other hand, does not show the following assertions that exist:

iterable.shouldMatchInOrder(assertions)
iterable.shouldMatchInOrderSubset(assertions)

Ref: https://github.com/kotest/kotest/blob/master/doc/matchers/core.md

**Comment by Kantis** [comment]
@zyxist all these were added in 5.2. What makes you say they don't exist? 

https://github.com/kotest/kotest/blob/master/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/collections/matchers.kt#L64

**Comment by zyxist** [comment]
OK, part 1 looks like Github issue - I'm still using 5.1.0 (was not able to migrate to 5.2.1 due to a bug in assertion library, and no time yet to move to 5.2.2), and I used Github search to check if the assertion exists in code on master branch before raising the issue, returned 0 results for me.

However, the second part still applies: https://github.com/kotest/kotest/blob/master/doc/matchers/core.md does not list those assertions - I'm not sure if this documentation is maintained or not, but if it is distinct from the one on kotest.io, maybe it would be good to remove it?

Maybe it would be also good to add the version selector to the documentation on website?

**Comment by Kantis** [comment]
The documentation at /doc seems deprecated indeed. See for instance [this commit](https://github.com/kotest/kotest/commit/1a8e74b1a71221563f83debc25f623e9a07a4d08). I think we should do the same for the matchers 🙂 

> Maybe it would be also good to add the version selector to the documentation on website?

Do you mean to add which version everything was added? Like...

| General                                 | Since |                                                                                                  |
|-----------------------------------|------|--------------------------------------------------------------------------------------------------|
| `obj.shouldBe(other)`           | 2.0        | General purpose assertion that the given obj and other are both equal                            |
| `expr.shouldBeTrue()`                 | 2.2   | Convenience assertion that the expression is true. Equivalent to `expr.shouldBe(true)`           |

Or something else?

**Comment by zyxist** [comment]
Regarding version selector - I meant something more like here: https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html

"Elasticsearch guide: 8.1 (current)" - the version is switchable and then you view the documentation for a particular version. I think having the current and previous versions will be sufficient, given that sometimes devs can't migrate to the newest version immediately.

Cleaning up unmaintained docs would be helpful, especially that it is currently indexed by Google.

**Comment by Kantis** [comment]
Regarding version selector - I just checked the framework we're using (Docusaurus) and it seems to have support for this. Perhaps we can create a new issue to implement version selection in docs? And this re-write this one to address unmaintained `/docs` folder? What do you think? 🙂

**Comment by Kantis** [comment]
Version selection has been added to kotest.io docs ✌🏼

**Comment by sksamuel** [comment]
What's the bug in 5.2.1 ?
