### ISSUE TITLE
Extensions and hooks don't work when you mixup DSL code (afterEach, beforeEach)

### ISSUE THREAD

**Issue by artemptushkin** [kotest/kotest#3077]
* `kotest version: 5.3.1`

I noticed that it's easy to mixup with the DSL to the scenario where your tests run and pass but hooks / extensions do not work, such as: `afterEach, beforeEach` and the corresponded classes: `AfterEachListener` and `BeforeEachListener`

Given:
```kt
class MyTest: FreeSpec({
  afterEach {
    println("this will never run")
  }
  "high level title" - {
      "children-title" - {
            println("this test will pass")
            "a" shouldBe "a"
      }
  }
})
```
Actual output:
```
> this test will pass
```
The expected output should contain `this will never run`, imo

At the same time when we only remove **dash** then we have a **workaround**:
```
"children-title" - {
```
to
```
"children-title" {
```
The output is as expected:
```
> this test will pass
> this will never run
```

I noticed this **only** having the highlight in Idea, otherwise, I have no clue how much time would it take to find the workaround, as it's not clear for the developer

<img width="383" alt="image" src="https://user-images.githubusercontent.com/22632802/175972073-6947912d-0254-427c-9f21-857a12705116.png">

Q: Could you please refer me to documentation, if it's there, where I could address this issue?
Q: Is it a bug or expected behavior?
Q: What is the difference between `FreeSpecTerminalScope` and `FreeSpecContainerScope`? I could not find any by this in the documentation

**Comment by Kantis** [comment]
Does this duplicate  https://github.com/kotest/kotest/issues/2988?

**Comment by artemptushkin** [comment]
@Kantis it's close but that's about the order and mine is about lambdas of different types (dash)

**Comment by Kantis** [comment]
It sounds like expected behaviour to me. [Containers](https://kotest.io/docs/framework/writing-tests.html#nested-tests) are not tests by themselves. The [docs for FreeSpec](https://kotest.io/docs/framework/testing-styles.html#free-spec) clearly states that the inner-most test must not use the `-` operand.

`afterEach` is invoked after each `TestType.Test` (not `TestType.Container`, unlike `afterAny`) as per docs [here](https://kotest.io/docs/framework/lifecycle-hooks.html).

As for:

>Q: What is the difference between FreeSpecTerminalScope and FreeSpecContainerScope? I could not find any by this in the documentation
Terminal scope is for defining tests (a leaf in the spec, where testing is done - the end of nesting) and it basically eliminates the possiblity of adding another level of nesting. I typically use containers to write some setup, and then tests to assert things on the setup. But you can use it however you like, pretty much 🙂

**Comment by artemptushkin** [comment]
@Kantis thanks, that's address the question and I see it's well documented especially [FreeSpec doc](https://kotest.io/docs/framework/testing-styles.html#free-spec)

I hope this closed issue will help someone if they end the same situation
