### ISSUE TITLE
Move json assertions to top level extension repo

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#3088]
What do you think about moving the json assertions into their own repo so we can release as and when?
@Kantis @LeoColman

**Comment by LeoColman** [comment]
I like it.
It's onboard on what we've been doing to other extensions.

**Comment by Kantis** [comment]
Disregarding the fact that it's sorta convention for now, which might be wrong.. 🤷 But I haven't felt limited by the release cadence of the main repo. I don't mind letting things take a while, and I think it's easier on consumers to not change the artifact coordinates and introduce a separate versioning series. My preference would be to keep it as-is. Do you feel it creates friction to have it in? Not a big deal to me either way 🙂

**Comment by sksamuel** [comment]
I'm pretty easy either way. The advantage of going to a separate deployment is a faster cadence, that's basically it.

**Comment by LeoColman** [comment]
I like to have it separate, as "Kotest json matchers" can be external to Kotest itself, which maybe should limit itself to only primite types of assertions

For new contributors:

- Much quicker to sync and execute tests from a smaller project with it's own ecosystem
- Easier to have a stabilized version of json assertions instead of depending on Kotest stability


So I think "Hey, I want to add new json assertions"

Doing that in Kotest project is more complicated than doing the same in a smaller library

**Comment by Kantis** [comment]
I agree with your points, but I'm not sure if I think it's enough to warrant the move. How do we weigh convenience for contributors versus convenience for users? Can we see how many are currently using the `kotest-assertions-json` dependency?

**Comment by sksamuel** [comment]
Yeah there's stats inside maven central.
What's the objection, just that it's another repo to work in ?

**Comment by LeoColman** [comment]
That it's another coordinate, I think.

**Comment by sksamuel** [comment]
Closing this, doesn't seem to be huge support in favor.
