### ISSUE TITLE
Hi, it is question about AND in THEN scope.

### ISSUE THREAD

**Issue by jumpstreet13** [kotest/kotest#3143]
Please describe here what you would like to see documented.
Here is the issue about that - https://github.com/kotest/kotest/issues/594

But I tried it on my project and it worked like a charm. Maybe you can upgrade documentation about AND in THEN scope ? 
Or there are still problems with that approach ? 
![image](https://user-images.githubusercontent.com/19886384/183581149-d317305f-57bd-4025-a62f-0cf3b97101fc.png)

**Comment by sksamuel** [comment]
You shouldn't nest And inside Then because Then is a final state scope. This will probably break in a future release.

**Comment by Kantis** [comment]
This is already _not working_ since sam [fixed](https://github.com/kotest/kotest/commit/e33631f1cc3032a54d876ce3e44953bbe268ca6c) runtime-retention of DSL annotation in 5.4.0 

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/316857/186763242-1b73af96-b47b-47c0-a71b-4f62af2e4736.png">
