### ISSUE TITLE
shouldBe not requires corresponding type of parameter

### ISSUE THREAD

**Issue by schrek1** [kotest/kotest#3201]
I have question about shouldBe assertion.

I expected that it requires same type in hiearchy with type on called assertion.

code look like it:

![2](https://user-images.githubusercontent.com/17483576/188107538-10fb7590-8b73-487c-8c72-124a2ee0aa2a.png)

but when I refactoring type, it wouldn't make compile error:

![1](https://user-images.githubusercontent.com/17483576/188107648-8fb669b3-e592-4500-b687-4bf0c420f567.png)

it is bad cause I need fix test after run not in compile time

I would expect that it cause type incompatibility and failed build

**Comment by LeoColman** [comment]
You can use `obj.shouldBeInstanceOf<T>` to check for types.

`shouldBe` doesn't require the same type from both sides, as the equals method can vary wildly depending on the object being looked into. This is by design, and I don't think we'll be changing this

**Comment by sksamuel** [comment]
It won't change until Kotlin improves their type system.

`dog shouldBe Animal`
`animal shouldBe dog`

Can both be valid. If we limit LHS to equal RHS neither will work. If we limit LHS <: RHS or LHS >: RHS then only one direction will work.

**Comment by PrinceOfDubai24** [comment]
I'm not well aware of the issues that it has. It seems you already tried `@OnlyInputTypes`, not sure if anything has changed since then https://github.com/kotest/kotest/issues/1163 (yeah, it's still not a public annotation, you have to copy it)
Kotlin-test seems to also leverage it for its assertion methods.
It seems to work quite well for simple `equals` assertions.

Alternatively, you could also consider a custom inspection in the Kotest plugin just like IDEA has one for Junit and other methods.

I guess I will try to use a custom method for the time being to enforce checking correct types.
<img width="688" alt="image" src="https://user-images.githubusercontent.com/18502510/193936927-988aef53-d6c2-4b96-bae8-0b8f7633eb5d.png">
