### ISSUE TITLE
shouldThrow does not respect globalAssertSoftly

### ISSUE THREAD

**Issue by jlous** [kotest/kotest#3297]
kotest 5.4.2
I configure globalAssertSoftly=true, and it mostry works well, except in combination with shouldThrow.
This only reports 1 failure, and never prints "2":
```
    "should fail twice" {
        shouldThrow<NullPointerException> { println("1") }
        shouldThrow<NullPointerException> { println("2") }
    }
```

This only reports failures 1 and 2:
```
    "should fail 4 times" {
        1 shouldBe 0
        2 shouldBe 0
        shouldThrow<NullPointerException> { println("3") }
        4 shouldBe 0
    }
```
3 is printed, but the failure to throw an NPE is not reported
The final assert is not executed at all

**Comment by jlous** [comment]
In contrast, `runCathing{...} shouldBeFailure{ it shouldBe instanceOf(NullPointerException::class)} ` works as expected.
And is probably a nicer pattern anyway, but still.

**Comment by IvanPavlov1995** [comment]
From what I can see, `shouldThrow` does not respect soft assertions, neither global nor local. 
I have some doubts regarding possibility of such change. `shouldThrow<NullPointerException> { println("2") }` returns an instance of `NullPointerException` if it is thrown by the block and throws `AssertionError` otherwise. If assertion is in soft mode, `AssertionError` can be collected, but what should be returned instead of throwing `AssertionError`?

**Comment by sksamuel** [comment]
This cannot be implemented for the reasons @IvanPavlov1995 described.

`shouldThrow` returns the exception type or throws an error. In the case of soft assertions, and the shouldThrow fails (it _didn't_ throw an exception), there is no type to return to satisfy the function signature.

However we can add a variant that doesn't have a return, which I've done in this PR: https://github.com/kotest/kotest/pull/3476
