### ISSUE TITLE
Kotest's @Language is prioritized over IntelliJ's, prompting for an opt-in

### ISSUE THREAD

**Issue by RBusarow** [kotest/kotest#3387]
Kotest: 5.5.5
Kotlin: 1.7.21 and 1.8.10
Gradle: 7.5 and 7.6

The new overloaded `@Language` annotation is prioritized over the IntelliJ one, in the IDE and during Gradle builds.

```text
w: [...]Main.kt:4:34 This declaration needs opt-in. Its usage should be marked with '@io.kotest.common.KotestInternal' or '@OptIn(io.kotest.common.KotestInternal::class)'
```

![img](https://user-images.githubusercontent.com/9890900/216869531-488626aa-6fb8-4b9b-8b67-d3dd4980e4e5.png)

reproducer project: https://github.com/RBusarow/Kotest-Language-repro

**Comment by gabrielittner** [comment]
Kind of related, we are getting build errors for Android instrumentation tests with 5.5.5
```
Execution failed for task ':module:checkDebugAndroidTestDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class org.intellij.lang.annotations.Language found in modules annotations-24.0 (org.jetbrains:annotations:24.0.0) and kotest-common-jvm-5.5 (io.kotest:kotest-common-jvm:5.5.5)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

**Comment by Kantis** [comment]
@aSemy what do you think is best way forward?

**Comment by aSemy** [comment]
Ah that's a shame. I'm not sure how to fix it, it was a bit of a hack to begin with (albeit one that was suggested by JetBrains). I also don't know how to create automated tests for problems...

So since it's causing errors, then remove it. I'll make the PR.

UPDATE: Ah I realise the mistake I made, I think I can fix it. 

1. change `expect annotation class Language` to `expect annotation class KotestLanguage`
2. in non-JVM platforms, copy-paste the JVM `@org.intellij.lang.annotations.Language` implementation
3. then in all platforms, use 
   ```kotlin
   actual typealias KotestLanguage = org.intellij.lang.annotations.Language
   ```

   Which in non-JVM targets will use the copy-pasted annotation, and in JVM targets the original annotation.
