### ISSUE TITLE
Codepoint.ascii() does not cover the whole ASCII range.

### ISSUE THREAD

**Issue by sielenk-yara** [kotest/kotest#3426]
**Kotest 5.5.4**

The generator only generates codepoints from " " (32) to "z" (122) which is not even the entire printable ASCII range!

According to [Wikipedia: ASCII](https://en.wikipedia.org/wiki/ASCII), the ASCII code points are 0..127 and the printable ones are 32..126.

**Comment by echo304** [comment]
I'll pick this up :)

**Comment by echo304** [comment]
IMO, it should go with printable ascii characters which is 32..126 (" " to "~")

**Comment by sielenk** [comment]
Why? Now this still does not return the ASCII code points as defined by the standard.

This does not respect the principle of least surprise when implementing an API: 
There is a well known (even official) specification defining ASCII as 0..127 but this is supposed to do something else?

**Comment by sksamuel** [comment]
What about .ascii() and .printableAscii() ?

**Comment by sielenk** [comment]
Would be better and kind of fits into the things already there in `codepoints.kt`.

But is it a good idea to leave the "nonprintable" codepoints out when testing?

I encountered this surprise while I was testing code serializing from/to strings with "|" used for a special purpose and was surprised, when it never showed up. I knew it is within the ASCII range.
And since the "nonprintable" codepoints tend to show up in unexpected places (e.g. when people copy/paste text with newlines and/or tabs), having them present in random test strings can be very valuable.

**Comment by sksamuel** [comment]
If we provide both variants, then it's on the developer to choose the
right one.

**Comment by sielenk** [comment]
Sure, just go ahead and do it.

But remember to update the [documentation](https://github.com/kotest/kotest/blob/c3cbb34c0292deb569722d7aa7adabeef71c16aa/documentation/versioned_docs/version-5.5/proptest/genslist.md), too!

**Comment by sielenk** [comment]
Maybe something to lighten the mood and as a disclaimer to not seem mean:

Just trying to be the QA engineer here, @sksamuel. I really like Kotest and am using it in a commertial software product as test framework.

I do appreciate your contribution, @echo304. Building good software is a lot of work and anyone helping is certainly welcome!

**Comment by echo304** [comment]
All the feedbacks and ideas are welcome 👍 

I'm just curious about adding 'ascii code points including non-printable' is necessary as of now. 🤔 
Since [documentation](https://github.com/kotest/kotest/blob/c3cbb34c0292deb569722d7aa7adabeef71c16aa/documentation/versioned_docs/version-5.5/proptest/genslist.md) mentioned that it generates random 'printable' strings, I believe fixing `Codepoint.ascii()` to return all printable ascii strings meets current requirements. And it covers reasonable usage of 'ascii' testing stuff.
<img width="1017" alt="스크린샷 2023-02-28 오후 5 01 35" src="https://user-images.githubusercontent.com/16456651/221790991-d1442939-276c-4609-89a7-c19c2f834398.png">

And not to break anything that uses `Codepoint.ascii()`, I think adding new method such as `Codepoint.asciiIncludingControlCharacters()` if needed. (Be noted that method name is just an example)

**Comment by Kantis** [comment]
What do you think about having `Arb.string` use `Codepoint.printableAscii()`, and to make `Codepoint.ascii()` include the entire ascii range?

**Comment by echo304** [comment]
@Kantis I agree with that approach but I'm not sure if `Codepoint.ascii()` is revealed to end-user or not due to lack of understanding of the project 😏 Is it ok from the view of compatibility? If it's ok, I'm on it.

**Comment by sielenk-yara** [comment]
@echo304 I would assume `Codepoint` it not (yet) revealed to the documentation reading end-user due to the fact that documentation is often forgotten when adding cool new features... This is not a government or big business project starting with loads of specification documents!

@Kantis Looks good to me.

**Comment by Kantis** [comment]
> @Kantis I agree with that approach but I'm not sure if `Codepoint.ascii()` is revealed to end-user or not due to lack of understanding of the project 😏 Is it ok from the view of compatibility? If it's ok, I'm on it.

It could break tests which rely on `ascii()` returning only printable chars. But I think we can put this change in 6.0?

**Comment by echo304** [comment]
Got it. Let me show you the code.
