### ISSUE TITLE
Use Kotlin Binary compatibility validator to prevent unwanted breaking binary changes 

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#3430]
Currently we have no automated way of telling how/if the API of Kotest changes. By having automatic tests on the API surface, we can easily see if a PR contributes breaking changes.

## Proposed way of working
Using https://github.com/Kotlin/binary-compatibility-validator,  GH workflow would run `apiCheck` on PRs, failing builds where the API changes. 

In order to submit a PR with API changes, contributor would have to run `./gradlew apiDump` to update the API snapshot with their changes.

**Comment by nomisRev** [comment]
We've had good success in Arrow using this tool to maintain binary compatibility. A couple things to note:
 - It only tracks JVM binary, not native or JS binaries
 - It's still possible to break source compatibility without breaking binary compatibility by for example changing the name of parameters

Hopefully these issues will be fixed soon. Kotlin has it on the roadmap to improve maintaining binary compatibility for klib, but nevertheless it's been really useful in Arrow to be able to track binary compatibility in reviewable files. I.e. besides binary changes becoming reviewable it's possible to compare commits and see how the binary evolved. Since we added this one version before 1.0.0 I can now easily go back in history and easily check the changes in the binary. Also you can easily double-check there is no binary breaking changes before a new release.

**Comment by Kantis** [comment]
Bump. @sksamuel do you think it's worth trying out, or would it be bad for the momentum of Kotest?

**Comment by sksamuel** [comment]
If you want to include it I think it won't hurt. We should try our best to not break things.
