### ISSUE TITLE
property testing: generate two maps that share some keys

### ISSUE THREAD

**Issue by abendt** [kotest/kotest#3459]
# Problem

I was working on some [property tests for code](https://github.com/arrow-kt/arrow/pull/2980) that needs two maps `Map<A,B>` for input.
Initially i specified the maps like this:
```
checkAll(Arb.map(Arb.long(), Arb.boolean()), Arb.map(Arb.long(), Arb.boolean())) { a, b ->
   …
} 
```
When checking the test coverage i found that some of the code branches were never executed. In the code there are specific cases when a specific key is present only in the left, right or in both maps. I learned that the above code usually does not generate maps that share any keys.

Slack: https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1679137444494889

# approach 1

I tried out some ways to improve that. What I have come up with so far is a specialized Arb with the following signature:
```
fun <K, A, B> Arb.Companion.map2(
   genK: Gen<K>,
   genA: Gen<A>,
   genB: Gen<B>,
   size: IntRange = 0..1000,
   slippage: Int = 10,
   shared: IntRange = 0..100
   ): Arb<Maps2Result<K, A, B>> = ...
```

It generates two maps, You can specify the size range for both maps and also specify the percentage of keys both maps should share. Within the test you need to destructure the param to access the both maps:
```
checkAll(Arb.map2(Arb.long(), Arb.boolean(), Arb.boolean())) { (a, b) ->
   …
} 
```

See https://github.com/kotest/kotest/pull/3460 for my implementation of the described approach

# alternative approach

see https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1679174980343619?thread_ts=1679137444.494889&cid=CT0G9SD7Z for ideas to add some functions that can be composed to fulfill this need

**Comment by myuwono** [comment]
Thank you @abendt! 🙌  I have a few things that I'd probably consider before adding this into kotest. Obviously having this in kotest would also mean we will have to eventually evolve it into map2, map3, ... mapN.

In my humble opinion we should rethink whether adding this into kotest is the right thing to do... This arb is very domain specific and arguably has a rather niche usecase when we're thinking of it in the more general sense. As it stands, there are many ways to solve this.. either (1) a concrete sealed class or (2) a data class with options (since nulls doesn’t stack…), or (3) if you're using Arrow, there's also a type called `Ior<A, B>` that does that. 

This is something that I just quickly wrote with option (2). Here I’m assuming we have access to an `Option<A>` type, can be homegrown or you can get that from Arrow, can be anything. The reason to use `Option<A>` instead of nulls is because null does not stack: i.e. a double nullables `A??` isn’t possible, whereas in option it’s possible to have `Option<A?>`. This way you can have an arb that contain nullables, to construct desctructured map of `Map<K, A?>` from it.

Here's a possible code snippet

```kotlin
data class Value3<A, B, C>(val first: Option<A>, val second: Option<B>, third: Option<C>)

data class Map3<K, A, B, C>(val first: Map<K, A>, val second: Map<K, B>, val third: Map<K, C>)

fun <A, B, C> Arb.Companion.value3(
  arbFirst: Arb<A>,
  arbSecond: Arb<B>,
  arbThird: Arb<C>,
  ... // other params that you'd want to add to determine the mixing ratios of A, B, and C, right now this assumes equal probability of mixing
): Arb<Value3<A, B, C>> = Arb.bind(
  Arb.option(arbFirst), 
  Arb.option(arbSecond),
  Arb.option(arbThird),
  ::Value3
)

fun <K, A, B, C> Map<K, Value3<A, B, C>>.destructured(): Map3<K, A, B, C> {
  val firstMap = mutableMapOf<K, A>()
  val secondMap = mutableMapOf<K, B>()
  val thirdMap = mutableMapOf<K, C>()
  this.forEach { key, (maybeFirst, maybeSecond, maybeThird) ->
    maybeFirst.onSome { firstMap[key] = it }
    maybeSecond.onSome { secondMap[key] = it }
    maybeThird.onSome { thirdMap[key] = it }
  }
  Map3(firstMap, secondMap, thirdMap)
}
```

and by extension therefore we can define `Arb.map3` which is a shorthand of `Arb.map` followed by `.destructured()`
```kotlin
fun <K, A, B, C> Arb.Companion. map3(
  arbKey: Arb<K>,
  arbA: Arb<A>,
  arbB: Arb<B>,
  arbC: Arb<C>,
  // etc.. other params
): Arb<Map3<K, A, B, C>> =
   Arb
    .map(arbKey, Arb.value3(arbA, arbB, arbC, ...)) // otherParams goes here as appropriate
    .map { it.destructured() }
```

the arb of interest can therefore be written as follows, and then used in your test

```kotlin
val arbOfMapWithSharedKey: Arb<Map3<Key, First, Second, Third>> =
   Arb.map3(arbKey, Arb.value3(arbFirst, arbSecond, arbThird))

test("should handle maps with shared keys") {
  checkAll(arbOfMapWithSharedKey) { (mapKeyToFirst, mapKeyToSecond, mapKeyToThird) -> // these maps will have shared keys
    ...
  }
}
```

I like to think of an Arb  as individual population of types.

Each arb will be sampled independently to other arbs within the checkAll params. This means, if we were to have two arbs interrelated to one another, such has to be declared as part of the same population. This exercise is an example of what happens very often in more diverse and complex usecases.. In real use case, one would have various data classes and would have used either an `Arb.bind` or compositions with `map` and `arb.flatMap { }` or using `arbitrary { }` builder to create complex data classes and structures (e.g. maps and lists).

With that in mind, in my humble opinion this use case is arguably very specific to individual requirements. i.e. the usefulness of this arb really depends on how `Arb.value3(...)` and how their mixing ratios, and more importantly how they interact with the rest of the system under test. Perhaps it's more appropriate to have this in the implementers’ personal repository as there all the mixing of parameters, as well as how a data class is created would make a lot more sense if it is declared there.

**Comment by abendt** [comment]
I chose now to implement this approach using tuples (Pair and Triple).
My reason for tuple instead of `Ior` is that i needed two implementations (for 2 and for 3 maps). When using `Pair` and `Triple` as the container both implementations can be quite similiar. I tried out to nest to Iors for the 3 map case: `Ior<A, Ior<B,C>>`. This works but is a bit harder to read imo.

Also  i did not need to use Option as i didn't need nullable values in the maps.

thanks a lot @myuwono!
