### ISSUE TITLE
`shouldBeInstanceOf` does not work with generics

### ISSUE THREAD

**Issue by kirillzh** [kotest/kotest#3524]
Kotest 5.5.4

Following test passes when it should not:
```kotlin
test("test") {
  listOf(1).shouldBeInstanceOf<List<String>>()
}
```

Same result with `shouldBeTypeOf`

[Slack discussion](https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1683614204835339)

**Comment by echo304** [comment]
Is this issue should be fixed?
If no one is working on this issue, can I get to work on it?

**Comment by zakhenry** [comment]
Note this may not be possible as while a generic can be reified, it does not appear that the generic of a generic can be inferred.

Possibly relevant - kotlin.test explicitly states that due to type erasure only one level of generic can be asserted on.
 https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/assert-is.html

**Comment by sksamuel** [comment]
Have checked into this.

The KClass.isInstance method returns true for kinds of arity 2, so there is not much we can do here.

Going to close.
