### ISSUE TITLE
@RequiresTag does not work as expected

### ISSUE THREAD

**Issue by zakhenry** [kotest/kotest#3531]
**Which version of Kotest are you using**
5.6

Reopening #3274 (marked as bug but closed due to inactivity).

*Expected behavior*:
Adding a `RequiresTag()` annotation to a spec class prevents that class from being run *unless* the tag is in the list of active tags in the argument (i.e. not negated, or no tags specified)

*Observed behavior*:
Adding a `RequiresTag()` annotation to a spec class has no effect *unless* some other tag is specified (i.e. TagExpression is not null)

concrete example:
I have a tag `object EndToEnd: Tag()` that I don't want to run by default when `./gradlew myproject:test` is run. I've added `@RequiresTag("EndToEnd")` to my e2e spec classes. 

workaround: I could negate it with `./gradlew myproject:test -Dkotest.tags="!EndToEnd"` however that seems to defeat the purpose of `RequiresTag()` annotation

**Comment by Kantis** [comment]
Related work was done in #3189, could be used as inspiration for how to test and fix this.

**Comment by zakhenry** [comment]
@Kantis FYI I've proposed a fix at #3532 

I'm a little concerned this could be a breaking change for some, however I'll leave that call up to you folks 😁

**Comment by Kantis** [comment]
This affects Kotest at least since v5.0.0, so the defect has been around a long while.. Perhaps it warrants a bit of a discussion on the semantic difference between `@Tags` and `@RequiresTag` and how they interact with `TagExpression`.

IMO it would make sense if `@RequiresTag` only runs on the _presence_ of the required tag.. Whereas `@Tags` provides selectors for _possible_ inclusion/exclusion.

E.g. a test annotated with`@RequiresTag("windows")` should not run with the tag expression `!slow`
A test annotated with `@Tags("slow", "integration")` should run on empty expression, `!unit-test`, and be ignored for the expression `!slow`

This would definitely be breaking behaviour though, since currently negated expressions will satisfy `@RequiresTag`. If we decide to go for it,  we need to hold it until  6.0.

If we decide to just fix `@RequiresTag` to not be satisfied by empty tag expression I'm not sure if we can release it as a bug fix. IMO it would definitely be a bug fix, but it could break people's test setups. As mentioned, the defect has been present since at least 5.0.0
