### ISSUE TITLE
Status of kotest-framework-concurrency 

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#3580]
Since 2021 (Kotest 4.6), there are  improved versions of `retry`, `eventually`, etc in `kotest-framework-concurrency`. These improved versions are the ones currently documented on [kotest.io](https://kotest.io/docs/framework/concurrency/eventually.html). They're also still marked as Experimental. 

If these new versions offer improved APIs, should we start deprecating the old versions and replace the current utilities with the improved ones?

**Comment by sksamuel** [comment]
This is a good call. Those functions are really powerful and I use them all the time. The last iteration was added in 2021 as you say, and we've had two competing implementations since - one partially deprecated, one experimental. And I think the experimental ones are over complicated.

I've added in the linked PR a new set of functions which build on the past 2 years of experience, and simplify the many overloads. In the proposal, I have deprecated both existing sets, and added the new functions as non-experimental.

I also have removed the functions that were deprecated 2 years ago (only a handful).
