### ISSUE TITLE
Performance Regression in 5.7

### ISSUE THREAD

**Issue by recke96** [kotest/kotest#3670]
The update for `io.kotest:kotest-runner-junit5-jvm` from 5.6.2 to 5.7.0 introduced a huge performance regression.
Build time went from around 3 min to over 20+ min, with one run over 40 min.

Repo is open https://github.com/recke96/HemaTournament/actions/workflows/build-and-test.yml.

**Comment by kshired** [comment]
## Summary

@recke96 @sksamuel  This performance issue is likely due to this change. ( https://github.com/kotest/kotest/pull/3662 )

## Test Code

```kotlin
test("shouldContainExactlyInAnyOrder performance test") {
   checkAll(Arb.shuffle(listOf("1", "2", "3", "4", "5", "6", "7"))) {
      it shouldContainExactlyInAnyOrder listOf("1", "2", "3", "4", "5", "6", "7")
   }
}
```

## 5.6.2 

![CleanShot 2023-09-02 at 23 49 53](https://github.com/kotest/kotest/assets/36851531/e242ccd4-9dc2-44d1-a515-52e7ff176b4e)

73ms

## 5.7.0 

![CleanShot 2023-09-02 at 23 52 09](https://github.com/kotest/kotest/assets/36851531/f7cb0821-1757-429d-8fc6-043917b6636b)

4 sec

## 5.7.0 and revert #3662 PR

![CleanShot 2023-09-02 at 23 50 48](https://github.com/kotest/kotest/assets/36851531/8372521e-7b4c-4a8a-a25d-28fdf5fb67b7)

77 ms

**Comment by sksamuel** [comment]
Yes I just got there myself :)

There was a change yesterday to containExactlyInAnyOrder which is the cause. @pientaa

**Comment by sksamuel** [comment]
It's this line:

```
  val passed = expectedGroupedCounts.size == valueGroupedCounts.size && expectedGroupedCounts.all { (k, v) ->
    valueGroupedCounts.filterKeys { verifier.verify(k, it).areEqual() }[k] == v
  }
```

**Comment by kshired** [comment]
Yes, it looks like the default verifier, `ObjectEqualsEquality`, is affecting this performance issue.

**Comment by sksamuel** [comment]
It might be the fact we filter the valueGroupedCounts over and over.
It's prob O(n^2) now.

**Comment by sksamuel** [comment]
I think you're right @kshired looks like ObjectEqualsEquality

**Comment by kshired** [comment]
@sksamuel 

Yes, `shouldContainAll` has the same performance issue, so I think ObjectEqualsEquality is the cause.

**Comment by sksamuel** [comment]
I'm not sure ObjectEqualsEquality should be using eq,  I think the lookups are the cause.
The name implies object equality anyway, which eq isn't. Eq is a our special version of equals that takes into account other things.

**Comment by sksamuel** [comment]
I added a test for perf to avoid this in the future, but I notice the timeouts aren't working either. So another regression must be that the test timeouts are being ignored.

**Comment by pientaa** [comment]
Sorry for that! I didn't know that using ObjectEqualsEquality will cause such performance issues
