### ISSUE TITLE
v5.7.0+ no longer targets JVM 8

### ISSUE THREAD

**Issue by bddckr** [kotest/kotest#3678]
This branch/commit changed Kotest's released artifacts to target JVM 11 instead of 8. Is that intentional?
https://github.com/kotest/kotest/pull/3649/files#diff-512f24ca000c4a4211f731f7eae50d295161039d8c8018e5a9ee61d3a8182f33

(Note: While I personally don't use the multiplatform support, that was also changed to no longer target JVM 8: https://github.com/kotest/kotest/pull/3649/files#diff-f6cb6cfaa3d6d8164dd2c59721bcd0b673fe66c6c63743fbc8bd68660a9e4748)

As a user with pure Kotlin Android projects, I'm using a JVM target of 8. This change in Kotest is forcing me to upgrade to 11.

**Comment by BraisGabin** [comment]
Same issue. I can't find this change on the changelog so I assume it is not intentional. On detekt we give support to 8+ and with this change doesn't allow us to update kotest: https://github.com/detekt/detekt-custom-rule-template/pull/75. We don't use kotest on our main project for historical reasons but we promote the usage of it on our custom rule template.

**Comment by sksamuel** [comment]
I'll release 5.7.2 with this change reverted
