### ISSUE TITLE
kotest-extensions-blockhound depends on passing the CoroutineContext intact in 5.7.0+

### ISSUE THREAD

**Issue by ulrikrasmussen** [kotest/kotest#3702]
**Summary**
The Blockhound integration does not seem to work after Kotest `5.7.0`.

**Which version of Kotest are you using**
5.7.0

**Steps to reproduce**
See a minimal example at https://github.com/ulrikrasmussen/kotest-blockhound-integration-bug/blob/main/src/test/kotlin/com/example/kotestblockhound/Test.kt

The test is supposed to succeed because BlockHound throws a `BlockingOperationError`. However, no exception is thrown.

If you adjust `kotestVersion` in `build.gradle` and set it to `5.6.2` then the test succeeds.

**Comment by ulrikrasmussen** [comment]
It appears that this is due to https://github.com/kotest/kotest/pull/3622 which disables BlockHound by default on all threads unless those threads are running a coroutine with a `BlockHound.ContextElement` in the context. This behavior is at odds with the example in [the documentation](https://kotest.io/docs/extensions/blockhound.html#detection) and makes it impossible to use `kotest-extensions-blockhound` to detect blocking calls in coroutines that are not initiated from a test method. This includes e.g. event loops which are started and dispatched by blocking code so that we cannot extend their coroutine contexts from the test code.

I think I can work around the issue by not putting `kotest-extensions-blockhound` on the classpath and setting up BlockHound myself, but I am not sure if breaking these use cases was the intention of #3622

**Comment by OliverO2** [comment]
It is correct that the BlockHound extension now requires the `BlockHound.ContextElement` as an implementation detail. The mechanism has changed from a global setting to a coroutine-oriented one. Actually, this is in line with how Kotest works in general: There are a number of context elements, for example the `ErrorCollectorContextElement`, which Kotest needs to function. When stripping the coroutine context as done by the `runBlocking` call above, several Kotest mechanisms fail to work properly.

> This behavior is at odds with the example in [the documentation](https://kotest.io/docs/extensions/blockhound.html#detection)

Could you point out where the documentation suggests otherwise?

> and makes it impossible to use kotest-extensions-blockhound to detect blocking calls in coroutines that are not initiated from a test method.

While the extension by chance happened to cover that previously, it was never intended to be used independently of the Kotest framework. If you desire to use BlockHound checks for invocations outside Kotest, you can use BlockHound directly – though BlockHound does not provide any coroutine-local (or thread-local) way of enabling/disabling it (this is an exclusive Kotest feature).

> This includes e.g. event loops which are started and dispatched by blocking code so that we cannot extend their coroutine contexts from the test code.

Idiomatic Kotlin avoids invoking `runBlocking` and uses `withContext(Dispatchers.IO)` instead (which will never trigger `BlockHound`), [adding `limitedParallelism()` as necessary](https://blog.jetbrains.com/kotlin/2021/12/introducing-kotlinx-coroutines-1-6-0/#dispatcher-views-api).

> I think I can work around the issue by not putting kotest-extensions-blockhound on the classpath and setting up BlockHound myself, but I am not sure if breaking these use cases was the intention of https://github.com/kotest/kotest/pull/3622

While you can always use `BlockHound` directly without using the Kotest extension, you will lose the benefits of fine-grained coroutine-local control. But keep in mind that breaking the coroutine context chain will render other Kotest mechanisms non-functional, too.

**Comment by ulrikrasmussen** [comment]
Thanks for the clarification! We were piggy-backing on the global setting in our tests since we are using BlockHound to find blocking calls in a threadpool that we create ourselves, and judging from your response, this just happened to work but isn't within the use case. We will just set up BlockHound directly ourselves for those tests.

> Could you point out where the documentation suggests otherwise?

I think I confused myself by wrapping the example from the documentation in `runBlocking` which indeeds strips the coroutine context. The documentation does not include this, so I take back my statement.

I am closing the issue.
