### ISSUE TITLE
TestConfiguration::tags method usage from within test/container scopes

### ISSUE THREAD

**Issue by Kantis** [kotest/kotest#3793]
It would be nice if the method to add tags to the spec was not callable from within tests, since it doesn't seem to do anything at that point?  I think it would be possible to achieve this with `@DslScopeMarker` in some appropriate place.

**Comment by fwdekker** [comment]
I was using `tags(...)` inside of a `context` in a `FunSpec`, thinking this would tag the entire context. After upgrading to v5.8.1 I started getting errors. I found this issue, and learnt that my usage of `tags(...)` didn't actually result in my tests getting tagged! Oops! I'm now using `context("foo").config(tags = setOf(...))` instead :-)

Thank you and @sksamuel for the defensive programming. Making it fail _hard_ instead of making it some silent failure informed me of my mistake :smile:
