### ISSUE TITLE
[finalizeSpec, afterProject] don't work as document say for IsolationMode.InstancePerTest and IsolationMode.InstancePerLeaf

### ISSUE THREAD

**Issue by winkey728** [kotest/kotest#3794]
**Which version of Kotest are you using**
5.8.0

---

```kotlin
class MyTest : WordSpec({
    isolationMode = IsolationMode.InstancePerLeaf

    "a" should {
        "b" {}
        "c" {}
    }

    finalizeSpec {
        println("finalizeSpec")
    }

    afterProject {
        println("afterProject")
    }
})
```
The above code print
```
finalizeSpec
finalizeSpec
afterProject
afterProject
```
when `isolationMode = IsolationMode.InstancePerLeaf`, print
```
finalizeSpec
finalizeSpec
finalizeSpec
afterProject
afterProject
afterProject
```
when `isolationMode = IsolationMode.InstancePerTest`.

As the document [here](https://kotest.io/docs/framework/lifecycle-hooks.html) say `finalizeSpec`
>Called once per Spec, after all tests have completed for that spec.
>
>Regardless of how many times the spec is instantiated, for example, if InstancePerTest or InstancePerLeaf isolation modes are used, this callback will only be invoked once.
>
>The results parameter contains every TestCase, along with the result of that test, including tests that were ignored (which will have a TestResult that has TestStatus.Ignored).
>
>When running in the default SingleInstance isolation mode, then this callback and afterSpec are functionally the same since all tests will run in the same spec instance.

so I expect that the above code should only print "finalizeSpec" and "afterProject" once.

**Comment by OliverO2** [comment]
~`finalizeSpec` seems to work as documented:~
* ~with `InstancePerLeaf`, you'd get 2 invocations for leaf tests "b", "c".~
* ~with `InstancePerTest`, you'd get 3 invocations, 1 for container "a", 2 for leaf tests "b", "c".~

[Edit: The above is incorrect, see below.]

Regarding `afterProject`, there seems to be an interaction with the spec being created multiple times: Each spec creation invokes `afterProject`, so 2 project listeners are created for `InstancePerLeaf`, and 3 for `InstancePerTest`. With `SingleInstance` isolation, everything would work as you expected. I'd say having multiple project listeners being created by the same spec is unfortunate. @sksamuel any thoughts on this?

**Comment by Jadarma** [comment]
@OliverO2 I think you have accidentally mixed up `finalizeSpec` with `afterSpec`. That one, indeed, should run once per spec instance, of which there are 2, respectively 3 depending on isolation as you described. The issue talks about `finalizeSpec`, which according to the [lifecycle hooks](https://kotest.io/docs/framework/lifecycle-hooks.html) documentation, should only be executed _once_ after all tests within the spec have been executed, regardless of how many spec instances were created. It even mentions that, if a `SingleInstance` isolation is used, then `finalizeSpec` is effectively identical to `afterSpec`, but this is not the case in this issue.

**Comment by OliverO2** [comment]
@Jadarma You are right. I should have read the documentation (which was even correctly quoted above) more carefully. Thanks for correcting me!

**Comment by sksamuel** [comment]
There's subtle nomenclature at play here.

The `finalizeSpec` method is indeed only invoked once. However, you are not overriding a method here, but adding a fresh lambda each time the spec is created.

In other words, `finalizeSpec` here is invoked twice, each time adding a new listener. But the listeners themselves are then only invoked once.

Using randoms displays this,

```
class MyTest : WordSpec({
   isolationMode = IsolationMode.InstancePerLeaf

   "a" should {
      "b" {}
      "c" {}
      "d" {}
      "e" {}
   }

   finalizeSpec {
      println("finalizeSpec " + Random.nextInt())
   }
})

finalizeSpec -62242472
finalizeSpec -519606389
finalizeSpec -360639788
finalizeSpec -125785645
```

I agree that it is not intuitive however, but we must support allowing multiple finalize spec listeners to be added (eg for different resources to be closed). I'd be open to suggestions on how to make it clearer though.

**Comment by Jadarma** [comment]
@sksamuel I think the confusing part is this bit of the documentation _(regarding `finalizeSpec`)_:
> Regardless of how many times the spec is instantiated, for example, if InstancePerTest or InstancePerLeaf isolation modes are used, this callback _will only be invoked once_.

Which is false by your own example above, as it is called four times.

I also agree with your statement:
> I agree that it is not intuitive however, but we must support allowing multiple finalize spec listeners to be added (eg for different resources to be closed).

But isn't this precisely the use-case for `afterSpec` which will be executed once per spec _instance_ regardless? I mean in the case where you have `instancePerLeaf`, this will allow the `afterSpec` to cleanly dispose of resources as you say.

As it is now, it seems both `afterSpec` and `finalizeSpec` do the same thing because of the way they register the callbacks. But from the way they are named and how they were documented, the way I visualize it in my mind should be like:

```kotlin
val afterSpecCallbacks: Map<KClass<out Spec>, List<Lambda>> = /* ... */
val finalizeSpecCallback: Map<KClass<out Spec>, Lambda> = /* ... */ 
```

So there can be any number of `afterSpec` callbacks, that would handle resource clearing and the like depending on how many specs were instantiated, but _at most one_ `finalizeSpec` callback which allows for some other form of orchestration. An example would be for a database testing spec, every instance creates a schema, and drops it in `afterSpec` and on `finalizeSpec` you close the entire database connection since it's no longer needed.

Does that make sense?

**Comment by sksamuel** [comment]
> @sksamuel I think the confusing part is this bit of the documentation _(regarding `finalizeSpec`)_:
> 
> > Regardless of how many times the spec is instantiated, for example, if InstancePerTest or InstancePerLeaf isolation modes are used, this callback _will only be invoked once_.
> 
> Which is false by your own example above, as it is called four times.
> 
> I also agree with your statement:
> 
> > I agree that it is not intuitive however, but we must support allowing multiple finalize spec listeners to be added (eg for different resources to be closed).
> 
> But isn't this precisely the use-case for `afterSpec` which will be executed once per spec _instance_ regardless? I mean in the case where you have `instancePerLeaf`, this will allow the `afterSpec` to cleanly dispose of resources as you say.
> 
> As it is now, it seems both `afterSpec` and `finalizeSpec` do the same thing because of the way they register the callbacks. But from the way they are named and how they were documented, the way I visualize it in my mind should be like:
> 
> ```kotlin
> val afterSpecCallbacks: Map<KClass<out Spec>, List<Lambda>> = /* ... */
> val finalizeSpecCallback: Map<KClass<out Spec>, Lambda> = /* ... */ 
> ```
> 
> So there can be any number of `afterSpec` callbacks, that would handle resource clearing and the like depending on how many specs were instantiated, but _at most one_ `finalizeSpec` callback which allows for some other form of orchestration. An example would be for a database testing spec, every instance creates a schema, and drops it in `afterSpec` and on `finalizeSpec` you close the entire database connection since it's no longer needed.
> 
> Does that make sense?

Yes it makes sense, but it's an interpretation of `finalizeSpec` that is not how it works. `finalizeSpec` doesn't ensure that only one listener is registered. It ensures that each registered listener is only invoked once.

We have to support multiple finalize spec listeners. For example, the spring extension may register one to close down its test profile. And the test containers extension can register one to close down the database.

It's definitely not intuitive because this thread shows how it can be confusing. You're expecting the callback to only be registered once, regardless of the fact the registration invocation is executed in each created spec. My code demonstrates that each registered callback is not executed twice, but is in fact four different callbacks.

As it stands, the finalizeSpec method inside the spec itself is kinda useless. We could change its behavior to do what you're expecting, that the system remembers if the block has been invoked, and if so, ignores further registration attempts. Or we could just remove it and force you go to via the FinalizeSpecListener interface and register them globally or via annotations like you can today. That would be similar to how PrepareSpecListener works - there is no method inside the spec itself because the spec already exists at that point.

That would be a breaking change, but could make its way into 6.0

**Comment by Jadarma** [comment]
@sksamuel I think I finally understand the underlying issue here. I will try to summarize the facts in hopes of clearing up the confusion in this thread.

Let's take the following code as reference:

```kotlin
class Test : FunSpec({

    isolationMode = IsolationMode.InstancePerLeaf

    val id = Random.nextInt()

    afterSpec { println("After $id") }
    finalizeSpec { println("Finalize $id") }
    afterProject { println("Project $id") }
    test("a") {}
    test("b") {}
}
```

This executes:
```
After -1021759564
After -1744915
Finalize -1021759564
Finalize -1744915
Project -1021759564
Project -1744915
```

And now let's consult the [lifecycle hooks documentation table](https://kotest.io/docs/framework/lifecycle-hooks.html) which states the following:

> `afterSpec`
> If a spec is instantiated multiple times - for example, if InstancePerTest or InstancePerLeaf isolation modes are used, then this callback will be invoked for each instantiated spec, after the tests that are applicable to that spec instance have returned.

This is correct! ✅

It also states this, which we should keep in mind:

> This callback should be used if you need to perform cleanup after each individual spec instance. If you need to perform cleanup once per class file, then use finalizeSpec.

Then, we have:

> `finalizeSpec`
> Regardless of how many times the spec is instantiated, for example, if InstancePerTest or InstancePerLeaf isolation modes are used, this callback will only be invoked once.

This is technically true, but misleading! ⚠️
We can see that it essentially acts just like `afterSpec`, but called after all other `afterSpec`s have finished.
Because even though it only runs once, it's _registered_ once per spec, and since isolation mode creates multiple of them, this leads to the duplication in the output!

But also, `finalizeSpec` is just the opposite of `prepareSpec`, which also states the same about only being invoked once.
Unlike `finalizeSpec` however, `prepareSpec` does not have an equivalent inside the Spec, because logically it can't. It must run _before_ spec initialization, so it cannot be registered by a Spec, since that happens after it.

Samuel is also correct about this:

> We have to support multiple finalize spec listeners. For example, the spring extension may register one to close down its test profile. And the test containers extension can register one to close down the database.

In the context of extensions, it is needed to support multiple callbacks because they can fulfill different roles!

## How to reconcile this?

The documentation is correct about the lifecycle, but the fact that `finalizeSpec` can be registered from within a Spec creates this ambiguity and confusion, and also just duplicates the functionality of `afterSpec`. Also, a `finalizeSpec`, should only have access to the class type of the spec, but since it is registered as a lambda, there is nothing preventing the user from passing in instance-specific data in the closure.

Therefore I agree with Samuel that, if this will be planned for a breaking change in 6.0, that the `finalizeSpec` be removed from within a Spec, and only be allowed to register via extensions like `PrepareSpecListener` is!

The `afterProject` is in the same boat it is un-intuitively duplicated when not using single instance isolation, resulting in the duplicates mentioned by OP, and is not even mentioned in the above documentation. Maybe it should be removed as well and only available via extensions / listeners.

Cleaning up resources for individual spec instances continues to be done via `afterSpec`, which works as expected from reading the documentation.

Or, another alternative would be to throw an illegal state exception if the spec instance `finalizeSpec` and `afterProject` are used within a spec that is _not_ in single instance mode, to not have to write a custom extension if you don't need it. But that's a runtime error, so I don't think it's the right call.
