### ISSUE TITLE
JsonNode string representation is always an empty array

### ISSUE THREAD

**Issue by alturkovic** [kotest/kotest#3819]
**Which version of Kotest are you using**
5.8.0

When comparing two Jackson `JsonNode` instances and the test fails, the output is always an empty array:
```
test("compare JsonNodes") {
    TextNode("first") shouldBe TextNode("second")
}
```
results in:
```
expected:<[]> but was:<[]>
Expected :[]
Actual   :[]

io.kotest.assertions.AssertionFailedError: expected:<[]> but was:<[]>
```

I guess it is due to `JsonNode` being `Iterable`? Is there any way to get actual json output from `JsonNode.toString()` or something similar instead?

**Comment by kshired** [comment]
This problem due to implementation of kotest's `IterablePrint` and jackson-databind's `JsonNode`

https://github.com/kotest/kotest/blob/8fb0b73b3b24b24b23064cc5614c41c0db5a4431/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/print/Printers.kt#L40

https://github.com/kotest/kotest/blob/8fb0b73b3b24b24b23064cc5614c41c0db5a4431/kotest-assertions/kotest-assertions-shared/src/commonMain/kotlin/io/kotest/assertions/print/IterablePrint.kt#L6

In above code `a.toList()` try to make `JsonNode` to List, but `JsonNode`'s `iterator` function always return `emptyIterator`.

**Comment by Kantis** [comment]
Duplicates https://github.com/kotest/kotest/issues/3542
