### ISSUE TITLE
Sharing Flow in couroutineTestScope hangs tests

### ISSUE THREAD

**Issue by MiSikora** [kotest/kotest#4035]
**kotest 5.9.0**

When a flow is shared in `coroutineTestScope` the whole test hangs and fails to finish.

```kotlin
import io.kotest.core.coroutines.coroutineTestScope
import io.kotest.core.spec.style.FunSpec
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.flow.shareIn

class DummySpec : FunSpec({
  test("dummy").config(coroutineTestScope = true) {
    flowOf(1).shareIn(coroutineTestScope, SharingStarted.Lazily)
  }
})
```

**Comment by mirageoasis** [comment]
can you include import statement?
in my case `shareIn` method doesn't take Boolean Type as parameter

**Comment by MiSikora** [comment]
I updated the snippet. But I'm not not passing a boolean anywhere.

Ah, ok confusion came from the missing `import io.kotest.core.coroutines.coroutineTestScope`.

**Comment by OliverO2** [comment]
This is as expected:

A [shared flow](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-shared-flow/) set up like above never completes. After 1 minute, the test times out due to the default setting in `runTest`, which Kotest uses under the hood:

```
After waiting for 1m, the test coroutine is not completing, there were active child jobs: [StandaloneCoroutine{Active}@3f2bf145]
kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 1m, the test coroutine is not completing, there were active child jobs: [StandaloneCoroutine{Active}@3f2bf145]
```

Also, using a shared flow directly in `coroutineTestScope` seems tricky due to the [task scheduling of `runTest`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/run-test.html).

Using `coroutineTestScope.backgroundScope` and actually terminating the shared flow completes successfully:
```kotlin
flowOf(1).shareIn(coroutineTestScope.backgroundScope, SharingStarted.WhileSubscribed()).take(1)
```
