### ISSUE TITLE
When property testing strings using codepoints with unprintable characters, the output is not helpful

### ISSUE THREAD

**Issue by Zordid** [kotest/kotest#4152]
Currently, when using a simple `Arb.string` with codepoints like `Codepoint.ascii()` there will at some point be unprintable characters contained in the strings generated.

If such a test value fails the assertions, shrinking kicks in and in the end, you might end up with a message like this:

```
Property failed after 1 attempts
java.lang.AssertionError: Property failed after 1 attempts

	Arg 0: "" (shrunk from -&X74]"?@�mcayJL:,T`g{}ycwpC.Dux5"c1;F?@;So^)

Repeat this test by using seed -703120417207228322
```

Even worse. In IntelliJ, this shrunk string displays as `""` (like an empty string)! You simply do not know what exactly the problem might be.

So, my feature request is: in case of unprintable chars in a test string, please output the hex codes instead. Especially when the shrunk result is that single character that is causing the problem.

**Comment by Fleshgrinder** [comment]
With hex codes, do you mean Unicode code point notation? Non-standardized hex coding can be confusing because it’s not always clear what they represent. For instance, the JVM uses UTF-16 by default, so the hex codes of the individual bytes wouldn’t correspond directly to UTF-8 or UTF-32 code points.

Normalizing the output to Unicode notation (`U+xxxx` to `U+xxxxxxxx`) would likely be best, as it provides a standardized reference. However, this still depends on the underlying encoding, as it might not lead to the correct code point for encodings like KOI-8.

An alternative could be using [Unicode control pictures](https://www.unicodepedia.com/groups/control-pictures/), which can help represent control characters visually in a more standardized way.

**Comment by sksamuel** [comment]
Fixed in https://github.com/kotest/kotest/pull/4447
