### ISSUE TITLE
What's the best way to report IDE errors?

### ISSUE THREAD

**Issue by jmfayard** [kotest/kotest#5406]
Hello

recently the kotest plugin has filled my IDE with errors.
That's life, but my question is how to report them best?
Because for a Jetbrains or Google plugin, this goes straight to their issue tracker,
where they put the relevant data in a way that makes sense.
If I were to just copy/paste that into an issue, that would feel like spamming :P

**Comment by theHacker** [comment]
When reporting something, I include all I have:
- stacktrace
- what version (plugin, IntelliJ)
- how to reproduce (bullet point list, if I have concrete steps)
- all other things I noticed

For example: https://github.com/kotest/kotest/issues/5418

If you don't report the same/similar exception multiple times, I would assume nobody will consider that spamming 😄 
With IntelliJ stacktraces look closely because one issue can have a near infinite amount of different stacktraces
