### ISSUE TITLE
cannot download plugin version

### ISSUE THREAD

**Issue by huehnerlady** [kotest/kotest#5445]
Hi,
it seems the new IDE is not compatible with the kotest plugin yet?

When I try to reinstall it I get the following error:
![image](https://user-images.githubusercontent.com/12533979/117846712-fa03a400-b281-11eb-8f71-423a92f2aa37.png)

My intellij Version:
```
IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
```

**Comment by sksamuel** [comment]
Are you downloading manually

**Comment by huehnerlady** [comment]
@sksamuel no I try to install it via the intellij plugin marketplace
![image](https://user-images.githubusercontent.com/12533979/117926318-df204680-b2f8-11eb-8010-6c5c14b843c8.png)

![image](https://user-images.githubusercontent.com/12533979/117926340-e8111800-b2f8-11eb-82a3-0f870fac5e54.png)

**Comment by sksamuel** [comment]
For some reason its picking up the wrong version.
There is a 211 build.

plugin.PluginDescriptor(
   since = "211.6693.111", // this version is 2021.1
   until = "212.*",
   sdkVersion = "IC-2021.1",
   sourceFolder = "IC-211",
   deps = listOf("java", "org.jetbrains.plugins.gradle",
"org.jetbrains.kotlin:211-1.4.21-release-IJ6693.10")
)

Can you try uninstalling kotest, restarting and then searching again ?

**Comment by huehnerlady** [comment]
> Can you try uninstalling kotest, restarting and then searching again ?

@sksamuel thanks for reaching out. How can I uninstall it? For me it looks as if the plugin is not installed jet, otherwise I would not have an "install" button there, but an "update" buttin 🤔

**Comment by huehnerlady** [comment]
@sksamuel I think it was on my end, clearing the intellij cache did fix it 🙂 

I will close this issue now

**Comment by sksamuel** [comment]
Great, glad it's working.
