### ISSUE TITLE
Offer a way to set VM options programmatically

### ISSUE THREAD

**Issue by sschuberth** [kotest/kotest#5452]
Looks like the *kotest* plugin creates different kinds of IDEA run configuration depending on whether the whole spec or just a single test is run:

For whole specs a run configuarion of type "Gradle" is created, for single tests a run configuration of type "Kotest" is created. Now, I'd like to automatically set `-Dkotest.assertions.multi-line-diff=simple` as a VM options when running tests from the IDE. For "Gradle"-type run configurations this can be achieved by leveraging the [idea-ext plugin](https://github.com/JetBrains/gradle-idea-ext-plugin) and code like [this](https://github.com/oss-review-toolkit/ort/blob/e3d6511a4808df1093084d16efc5ab970435267b/build.gradle.kts#L89-L93). However, I currently see no way to do the same for "Kotest"-type run configurations, too.

Would an option to solve this be to make default Kotest run configurations use the same values as default Gradle run configurations?

**Comment by sksamuel** [comment]
Would this do the trick.

https://kotest.io/docs/intellij/intellij-properties.html

**Comment by sschuberth** [comment]
I don't see how, as I'd like to *only* use `-Dkotest.assertions.multi-line-diff=simple` when running tests from the IDE; when running from the CLI by directly invoking Gradle tasks (like on CI), I'd *not* like to have this property set.

**Comment by sksamuel** [comment]
Right I see.

Well in general, it's difficult to know when you're using the IDE vs gradle
because you can just invoke gradle from inside the IDE anyway.
What about if we added a system property that is set by the intellig kotest
plugin, and when that is set, we load properties from a file
`kotest.plugin.properties`. So kind of like what I linked you to, but only
for when you're using the intellij plugin.
The caveat would be if you're launching your tests using gradle from the
plugin.

**Comment by sksamuel** [comment]
You could also create project config that sets that value based on whether
idea.rt is on the classpath.

**Comment by sschuberth** [comment]
> You could also create project config that sets that value based on whether idea.rt is on the classpath.

Did that just now, works great, thanks for the idea!
