### ISSUE TITLE
Run all tests in a package ?

### ISSUE THREAD

**Issue by christopheblin** [kotest/kotest#5541]
When I right click on a directory, I can "Run 'All tests'" but this is launched with jUnit runner plugin (hence, for ex, you can not click on a test name to navigate to the source)

I tried to create a configuration manually but it seems there is no option to launch on a directory (or package)

For ex, that would be the same as when you create a jUnit configuration, you have the option 'Test kind' that can be set to 'All in package'

**Comment by LeoColman** [comment]
For some reason I always get surprised when people run `All tests`. I've never seen that intention in my life xD

I suppose you can still run all tests via `./gradlew test` for now, until we create an intention for all tests with KT

**Comment by christopheblin** [comment]
Just to explain more context.

The goal is not to run all tests of project (I indeed use that sometimes when I refactor the db or ... but this is unusual).

However, I often run all tests of a package (the package I am working on)

Also, note that running all tests with the jUnit plugin works, the problem is just that you can not navigate to a specific test failure (now that I installed the plugin, I navigate to the test and then run only the failing test so this is far better than before for me)

**Comment by LeoColman** [comment]
Yeah, JUnit's integration with Gradle wasn't a big priority for Gradle's team, and some features that we need are not yet available

That's why we don't have a very nice integration with JUnit right now (and probably never will).

Your report makes sense, thanks for it!

**Comment by sksamuel** [comment]
I need to update the plugin to capture the "run all tests" action.

**Comment by StragaSevera** [comment]
Ehm, the intention of running all tests is pretty clear - to make sure that you did not break something seemingly unrelated to the feature you are working on.

**Comment by LeoColman** [comment]
It is, yes.
Currently we can execute all tests with `gradlew test`.

**Comment by reevn** [comment]
Afaik running all tests with Gradle does not allow you to jump to the source of failed tests by clicking them in the run window, while this is possible when the tests are run with the plugin via "Run x".

To me it seems that this is actually a pretty desirable feature and executing via "Run all tests" would just more beneficial than the Gradle task.

**Comment by sksamuel** [comment]
Does right click on a package name not show the run all tests option? Using plugin 1.0.5+

**Comment by reevn** [comment]
Oh, it does. I was under the assumption that this is still an open point as both related issues were closed with `wontfix`, but it seems like this is supported now? 😄

I'm currently unable to really use the plugin because of https://github.com/mockk/mockk/issues/459 and just found this issue, but I should have made sure that this is even still relevant before reviving this thread. Sorry about that.

Thanks for clarifying!

**Comment by sksamuel** [comment]
Are you using intellij or android studio

**Comment by reevn** [comment]
I'm using Android Studio.

**Comment by sksamuel** [comment]
It seems to be a problem with the classpath setup in AS.

**Comment by reevn** [comment]
Even though the last few comments were unrelated to the topic, I can confirm that with the latest Kotest plugin version (`1.1.9`) everything seems to be working fine in Android Studio 🎉

**Comment by florianmutter** [comment]
Is this really solved? For me using plugin version 1.1.49-IC-213-EAP-SNAPSHOT it still does not use kotest to run tests if I right click on a package and select "Run tests" (see screenshot) 
![grafik](https://user-images.githubusercontent.com/32459530/148343966-2e630ab0-caa3-414f-8481-e59bb429b256.png)

**Comment by sksamuel** [comment]
What output do you get ?

**Comment by ptab** [comment]
I can confirm the same behaviour as @florianmutter: right-clicking on any package or test class only shows the regular _Run tests_ context menu dialog, which starts test execution using a Gradle configuration instead of a Kotest one.

Running tests with the Gradle configuration does work, but it does not offer the _Jump to source_ option from the _Run_ or _Debug_ pane, which is a serious productivity killer.  

Running an individual test by clicking on the ▶️ icon next to it executes it with a Kotest configuration as expected.

IntelliJ version: `2022.3`
Kotest plugin version: `1.2.63-223.4884.69-EAP-SNAPSHOT`
