### ISSUE TITLE
FreeSpec Reporting Question

### ISSUE THREAD

**Issue by JustinTullgren** [kotest/kotest#659]
Hi,

I have a question around FreeSpec reporting. I am only receiving the `should` message not the arbitrary nested strings in the gradle output and in intellij.

```kotlin
"A" - {
     "B" - {
                "C" - {
                    "should be ABC" {
                        "ABC" shouldBe "ABC"
                    }
                }
            }
        }
```

The report output is: `classname > should be ABC PASSED` and the same for the intellij reporter. 

Is this expected? 

Thanks!

**Comment by sksamuel** [comment]
Gradle won't display nested tests in output because gradle support for JUnit5 is broken.
See https://github.com/gradle/gradle/issues/4252 and https://github.com/gradle/gradle/issues/4912
It will be fixed at some point.

If you run the tests directly in Intellij it should be fine. Eg,

![image](https://user-images.githubusercontent.com/743706/52803141-5662c380-3079-11e9-97c6-8770647c69ad.png)

![image](https://user-images.githubusercontent.com/743706/52803161-5fec2b80-3079-11e9-9944-f1cbd47910d8.png)

**Comment by JustinTullgren** [comment]
Thanks!

**Comment by sksamuel** [comment]
You're welcome.
