### ISSUE TITLE
Split out assertions into separate project

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#681]
Let's discuss taking the KotlinTest assertions and making it a separate project - KotlinAssertions or something.

Pros:
 - Some people are under the mistaken impression the assertions are part of the test framework so maybe don't use them but they'd like to (understandable, it's not particularly clear they are stand alone)
- I believe KotlinTest assertions are the best available, and so this means people who like JUnit and Spek might be more included to use them (kind of related to point 1)

Cons:
- It might reduce KotlinTest's value proposition if it's _just_ a test framework. I know from doing Scala work I like the fact ScalaTest has it's matchers integrated.

**Comment by LeoColman** [comment]
We could separate it for code, documentation and issues separation

However, we may still keep it very referenced in KotlinTest's documentation, and keep it as a dependency.

This way, KotlinTest will still depend and provide KotlinTest-Assertions, but the opposite won't be true. What do you think?

**Comment by dave08** [comment]
Why not have one artifact with matchers and one without? I found advantages in KotlinTest over others even without the matchers.

**Comment by LeoColman** [comment]
I think that the point is that we want to centralize everything the developer needs to test Kotlin code within KotlinTest, and not having to mess with a shitload of dependencies

**Comment by dave08** [comment]
I meant (without matchers):
`testImplementation 'io.kotlintest:kotlintest-runner-junit5:3.2.1'`

or (for kotlintest with matchers):

`testImplementation 'io.kotlintest:kotlintest-matchers-runner-junit5:3.2.1'`

or maybe the opposite (with matchers default, without explicit in the artifact name).

**Comment by sksamuel** [comment]
So KotlinTest will always ship with the assertions because they are
lightweight and because some parts of KotlinTest integrate nicely with them
- like global soft assertions.
But this ticket is really about - should we make the assertions more
_visible_ as a separate project - KotlinTestAssertions / KotlinAssertons /
assertions4k / whatever name you like here.

**Comment by LeoColman** [comment]
I think KotlinTestAssertions is better. let's link both artifacts, eventhough they're separate.

They're only independent, but part of a bigger framework, that is KotlinTest itself

**Comment by sksamuel** [comment]
My vote is for KotlinAssertions as it's simpler and clear you don't need
KotlinTest.
But I will go with the consensus.
(We haven't even reached a decision on whether we will actually split them
up or not yet).

**Comment by LeoColman** [comment]
I am for splitting them up, but keeping the runners depending on them.

You can use Assertions by itself, but you get them with the runners aswell

**Comment by sksamuel** [comment]
I'd like to see feedback from a number of people before we decide.

**Comment by dave08** [comment]
The only thing is that those using other matcher frameworks or with very simple matching requirements will have their top level  intellij autocomplete with tons of functions that they are not using.

That was what first made me choose Spek, I was already used to Hamkrest and the like... By imposing the matchers and "polluting" the top level scope with functions, I had a very hard time switching to KotlinTest (after discovering the Spek drawbacks...), I wanted the test framework but still using my old matchers.

On the most recent version of one of our projects, I started using the KotlinTest matchers and finally got more used to them, sometimes still reverting back to others for specific things.

You're right about not having tons of deps (although JUnit and others do have them), but it would be a pity to alienate new potential users because of this.

**Comment by sksamuel** [comment]
That's a fair point @dave08.
It's no real hardship to add two dependencies rather than one.
But that being said, there are features in KotlinTest which build on the assertions support.

**Comment by jillesvangurp** [comment]
I think this is a good idea as well. Currently there are indeed a lot of competing libraries for testing and asserting in kotlin and a lot of that stuff needs to live side by side with Java testframeworks like junit that are still defacto used in a lot of places (e.g. the whole spring ecosystem). If you add multi platform kotlin to the mix, things get more complicated still since you then have to factor in e.g. karma or mocha or whatever on the js side + whatever they use for assertions.

I actually commented on this in a [reddit post ](https://www.reddit.com/r/Kotlin/comments/9sorfx/what_are_current_bestpractices_for_unit_testing/) some months ago. Still valid:

> I like separation of concerns and it seems there are more assertion frameworks than unit test frameworks. So as a consequence, my test classpath is kind of cluttered with stuff I don't really need. Feels wrong to me. I'd appreciate having separate dependencies. In larger teams there's always the risk of somebody using the wrong thing just because it is there.
> 
> So, for me it makes sense to separate these things since they don't really depend on each other. You could take kotlintest style bdd tests and use assertk, assertj, hamcrest, default junit 5 assertions, or whatever. That should work just fine. Likewise, I've used kotlintest should* assertions with several test frameworks now and I kind of like it (good work). IMHO both might end up being better frameworks if provided and maintained separately. Certainly both sides feel like there's room for improvement still.
> 
> For me BDD in Kotlin still feels a bit forced. There are limitations with respect to setting up shared test fixtures in nested tests that you wouldn't have in ruby or javascript. That largely defeats the point for me. I might go back to revisit this again but a few months ago I ended up doing vanilla junit 5 (which you end up having on the classpath anyway) and that seems to work well enough. Also, they are still planning to do their own style of BDD in a future 5.x. However, I'm not that convinced of their particular approach (see their issuetracker) or the apparent infatuation with having ton of stupid annotation verbosity.
> 
> Having this all this stuff bundled makes it even more awkward to use the assertions with other frameworks because now you are inheriting multiple things that you are not planning to use. E.g. in kotlintest in combination with testng, I somehow ended up with junit 4 and 5 on the classpath as well as assertions libraries coming along with all three of them. Add mojito and mockk to the mix and it becomes even worse. Ugly. If you are wondering, it's a legacy project that I'm slowly nudging towards kotlin. I have a ton of legacy tests that I need to keep happy and I don't have a lot of bandwidth for doing code migrations. The default assertions in junit have always been kind of limited. Thankfully, at least they've given up on repackaging and bastardizing hamcrest now.

**Comment by LeoColman** [comment]
I think we decided to keep assertions here for the moment. They're already a separate module, and people can follow all subprojects at once here.

If this need arises again in the future, we can revive this issue and keep the discussion going.

For now I'll close this.
