### ISSUE TITLE
FixtureSpec

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#692]
I see that in some test frameworks they like to create a _fixture_ and then refer to that in their tests.

First question - is there any fundamental difference between this:

```kotlin
class Demo : FunSpec() {

  fixture {
    User("sam")
  }
 
  test("testing usernames") {
    this.username.shouldNotBeEmpty() // this refers to the fixture
  }
}

```

and this:

```kotlin
class Demo : FunSpec() {
  override fun isolationMode() = InstancePerTest
  val user = User("sam")
  init {
    test("testing usernames") {
      user.username.shouldNotBeEmpty() // this refers to the fixture
    }
  }  
})

```

Or is it just a case of people don't know the latter exists and / or they prefer the syntax of the former ?

Secondly, is it worth adding this support into a `FixtureSpec` whereby the final test scope has the fixture as the receiver ?

**Comment by LeoColman** [comment]
I have no idea why a Fixture is needed if you can do the second option

**Comment by dave08** [comment]
In Spek, they required this (memoized) because they have a scanning step before the actual run. The value of such a construct in KotlinTest would be the fixture scope, meaning when the fixtures need to be recreated or cleared (in the case of mocks). In a sense, the IsolationMode does this, but it requires a new test class instance, whereas fixture recreation/reset might be more efficient.

That said, I always found fixture initialization inside a test class a bit messy (especially for integration tests...), I think Spek 2 allows declaring them outside and using them in the test class...

A good DI framework could also do this, but if well adapted for testing scope (test class/branch/leaf), there might be what to add in this.

Also, having access to declared mocks and not just the test subject is important, since some test setup depends on mock settings.

**Comment by sksamuel** [comment]
So it sounds like fixtures exist because other frameworks don't do the clever trickery that kotlintest does with it's isolation modes.

**Comment by dave08** [comment]
Partially right @sksamuel, since if there's too much fixture code in the test it could quickly get very messy, so having some kind of fixture support that could be plugged in to the different test levels, might be useful. Maybe an extension of listener that can return an object graph that's used in the test? (Using by and delegates according to prop names might be a plus...)

I didn't think it through completely though... there might be much to build on this idea if you like it.

**Comment by sksamuel** [comment]
It would be fairly straightforward to add a FixtureSpec that hides the isolation mode and provides an object graph used by the test. It would just delegate to isolation mode behind the scenes I suppose. Is that what you mean?
