### ISSUE TITLE
`config(threads=1)` seems to have no impact on `beforeSpec`

### ISSUE THREAD

**Issue by ThanksForAllTheFish** [kotest/kotest#710]
I have a library storing information in a thread local variable and when upgrading from version `3.1.11` to version `3.3.0` I found out my integration test with such library broke. I was able to recreate the issue in a smaller sample here: https://github.com/ThanksForAllTheFish/kotlin-test

It seems `kotlintest` runs `beforeSpec` in a different thread than the test itself, even when using `config(threads=1)`.

The sample test work as expected in version `3.1.11` and starts to fail from version `3.2.0`

**Comment by sksamuel** [comment]
I'm afraid this isn't going to be trivial.
The reason is that the before/after spec listeners run on a particular thread.
The code that invokes them, then needs to invoke the tests - but tests run inside a coroutine so people can run suspend functions.
A coroutine needs a dispatcher. It's easy to create a fresh dispatcher and then run a test plus its before/after test listeners all inside the same dispatcher.
But in order for the spec listeners and the tests to have the same underlying thread, a coroutine dispatcher would have to dispatch onto the calling thread, but this results in a dead lock.
I think the solution is make the spec executors run inside a coroutine scope themselves, and then the whole thing can run inside a single scope, unless otherwise requested. At the moment the coroutine boundary is at the test case level.
Short term solution - use beforeTest/afterTest if you can - those are guaranteed on the same thread and I've added a test to confirm.

**Comment by ThanksForAllTheFish** [comment]
Thanks for the feedback, it is no problem to me to move to `before/afterTest`.
