### ISSUE TITLE
Discussion - new syntax for before / after / etc

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#768]
At the moment to do a before/after you must override a method.
This means it has to be outside the init {} block.

If however it was all done with lambdas, then it could all live inside the init block and you could always do constructor init blocks.

Eg,

```
class MyTest() : FunSpec({

   test("test 1") { 
   }

   test("test 2") {

   }

   before {
    // inline before spec
   }

   after {
    // inline afer spec
   }

   beforeTest { 
    // inline before test, "it" refers to the test case
   }

   interceptors(inter1, inter2)

   interceptor { 
     // inline interceptor 
   }
})
```

I think this would mean we could ditch the init{} blocks completely.

**Comment by LeoColman** [comment]
I think we should keep both ways supported.
People coming from JUnit will have a very hard time to understand this syntax, and will probably always prefere the `@Before` way, and they should be able to.

As to ditch the `init`  blocks, I think there might be lots of reasons for people to want to use them. Both ways should also always be available (but if anyone prefers not using the init block, no prob)

**Comment by haroldadmin** [comment]
I use the init block because I need to extend my test classes with the `KoinTest` interface in order to inject dependencies. Passing tests as a constructor parameter does not allow me to use methods of the `KoinTest` interface. Losing init blocks would require us to investigate how else to support DI in test classes. However, I do agree that the before and after syntax you suggest looks super clean.

**Comment by sksamuel** [comment]
This is now in beta 4.0. You can still use the init block with the DSL methods.
