### ISSUE TITLE
Limit Parallelism for some specs

### ISSUE THREAD

**Issue by fraquack** [kotest/kotest#786]
I'd like to use both Parallelism and System Extensions in my project.
Unfortunately  System Extensions can't run concurrently.
A good trade-off would be to limit only the concurrent execution of specs that make use of System Extensions. I'm thinking about a sort of tag to identify these specs, translated in a lock that prevents their concurrent execution.

For instance:
```
class FooTest: StringSpec(concurrentTag = "environmentVariables"){
  withEnvironment("FooKey", "FooValue") {
    System.getenv("FooKey") shouldBe "FooValue"
  }
}

class BarTest: StringSpec(concurrentTag = "environmentVariables"){
  withEnvironment("FooKey", "BarValue") {
    System.getenv("FooKey") shouldBe "BarValue"
  }
}
```

Would this implementation be possible?

**Comment by sksamuel** [comment]
The problem is if you disable parallelism for one spec, you have to ensure that no other specs are running when you start this one, and then carry on with other specs afterwards.

Perhaps one solution would be a flag on config - `singleThreaded = true` or `parallelize = false` or whatever nomenclature you prefer, that essentially tells the engine to run these specs at the end, single threaded, after all the others have completed.

**Comment by fraquack** [comment]
> Perhaps one solution would be a flag on config - `singleThreaded = true` or `parallelize = false` or whatever nomenclature you prefer, that essentially tells the engine to run these specs at the end, single threaded, after all the others have completed.

This is actually better than my original proposal, because you can use the real environment variables in the test, mocking them only at the end.

**Comment by sksamuel** [comment]
Added for 3.4.
Annotate your class with @DoNotParallelize and those specs will never run in parallel.
