### ISSUE TITLE
Add matchers for Result

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#836]
Jetbrains added the `Result` type, a bit like the `Try` type from arrow.
We should add matchers for this.

**Comment by faogustavo** [comment]
I was trying to do this, but, unfortunately, I started to face some kotlin issues (I guess).
For some unknowing reason, the generic types influence on the Result class.
Here is the snippet that I made to test this.

```kotlin
/**
 * You can edit, run, and share this code. 
 * play.kotlinlang.org 
 */

fun main() {
    val result = Result.runCatching { "Test 01" }
    val errorResult = Result.runCatching { throw java.io.IOException("Some error happened") }
    
    println("Test")
    println(test("Test 01", result))
    println(test("Some error happened", errorResult))
    
    println()
    println("With generics")
    println(match("Test 01", "Some error happened").test(result))
    println(match("Test 01", "Some error happened").test(errorResult))
    
    println()
    println("With kotlintest dsl-like")
    println(result should match("Test 01", "Some error happened"))
    println(errorResult should match("Test 01", "Some error happened"))
}

infix fun <T> T.should(matcher: Matcher<T>) = matcher.test(this)

fun test(expectedValue: String, result: Result<String>) = if (result.isSuccess) {
    expectedValue == result.getOrNull()
} else {
    expectedValue == result.exceptionOrNull()?.message
}

fun <T> match(expectedValue: T, errorMessage: String) = object: Matcher<Result<T>> {
    override fun test(value: Result<T>) = if (value.isSuccess) {
        print("I'm a success")
        Pair(
            value.getOrNull() == expectedValue,
            Pair(value.getOrNull(), expectedValue)
        )
    } else {
        print("I'm an error")
        Pair(
            value.exceptionOrNull()?.message == errorMessage,
            Pair(value.exceptionOrNull()?.message, errorMessage)
        )
    }
}

interface Matcher<T> {
    fun test(value: T): Pair<Boolean, Pair<Any?, Any?>>
}
```

The result is this :point_down: 
```
Test
true
true

With generics
I'm a success - (false, (Success(Test 01), Test 01))
I'm a success - (false, (Failure(java.io.IOException: Some error happened), Test 01))

With kotlintest dsl-like
I'm a success - (false, (Success(Test 01), Test 01))
I'm a success - (false, (Failure(java.io.IOException: Some error happened), Test 01))
```

For some reason, when I pass the result to a generic, it creates a new "Success Result" and instead of getting "Test 01" from the `.getOrNull()`, its returning `Success(Test 01)`. 
The same is reproducible with the exceptions. When I send a failure, it becomes a `Success(Failure(TesteException))`.
I'll see if I can find some related bug on kotlin reporitory, but I think this issue will be blocked until we understand what is going on.

**Comment by faogustavo** [comment]
@sksamuel @Kerooker :point_up: 

---

I also create an issue on [kotlin issue tracker](https://youtrack.jetbrains.com/issue/KT-32228). Didn't find any similar bug.

**Comment by LeoColman** [comment]
I see.

I'll comment about this in KotlinLang's Slack, let's see if it's indeed a bug.

We can keep this on-hold for a bit :/

**Comment by Dico200** [comment]
The type T is a Result itself. So your `value` in your `test` override is a `Result<Result<*>>`

**Comment by Dico200** [comment]
Please swap the generics for concrete types and see if you can find the problem, this code is very unreadable here like this

**Comment by faogustavo** [comment]
> Please swap the generics for concrete types and see if you can find the problem, this code is very unreadable here like this

As I showed on the code that I posted before, I already tried without generic and it works. Unfortunately, the entire library is built upon those generics and doesn't make any sense to change that. Or even create a lot of repetition just for that.

They commented on the issue on kotlin issue tracker that it's a bug on kotlin/jvm about boxing/unboxing. They already added the task as a subtask from another group and maybe will have a solution after some time.

**Comment by sksamuel** [comment]
What's wrong with something like this: https://pl.kotl.in/zpkSnkEeD
That works, and you can add in the shouldBeFailure complement.

**Comment by faogustavo** [comment]
> What's wrong with something like this: https://pl.kotl.in/zpkSnkEeD
> That works, and you can add in the shouldBeFailure complement.

The problem is when you add one more level of [complexity like this](https://pl.kotl.in/8vLlEN0_q).
There is an issue that makes our syntax buggy. 
If you look carefully, you will see that in the message, instead of getting `Expecting Success(Test 01) to be Wibble`, we go `Expecting Success(Success(Test 01)) to be Wibble`. There is an "extra" Success being "added" when the value is passed as a parameter with all those levels using generics.

**Comment by sksamuel** [comment]
We could do it without the infix version for now: https://pl.kotl.in/5RZM9cKCT
And then add the infix version once they fix the bug ?
