### ISSUE TITLE
New matchers alias

### ISSUE THREAD

**Issue by sksamuel** [kotest/kotest#933]
Collection.shouldContainExactlyInAnyOrder -> Collection.shouldContainUnordered

**Comment by LeoColman** [comment]
I think `Unordered` is dangerous, it implies that if the collection is ordered, it's wrong

**Comment by sksamuel** [comment]
Ok maybe, the present name is very long though.

**Comment by segunfamisa** [comment]
Hey @sksamuel @Kerooker was there any conclusion on the preferred name?

What do you think about `Collection.shouldContainInAnyOrder`?

Also what happens when such API is changed? Is there a `@Deprecated` `@ReplaceWith` migration help provided?

I'm asking because I'm looking for a first issue I can contribute to on this project :) 

Thank you!

**Comment by LeoColman** [comment]
We usually do @Deprecated and @Replacewith, yes.

But we didn't discuss this new name enough. What do you think, @segunfamisa?

**Comment by sksamuel** [comment]
shouldContainInAnyOrder would work for things like [a,b,c,d] shouldContainInAnyOrder [a,c,d]

shouldContainAllInAnyOrder would work for [a,b,c,d] shouldContainAllInAnyOrder [d,c,a,b]

**Comment by segunfamisa** [comment]
Oh yes, that's correct @sksamuel I see what you mean now. 

I like it and it's a few characters shorter than the current name.

**Comment by atmikev** [comment]
@sksamuel  are all matchers up eligible to rename for conciseness or just `Collection. shouldContainExactlyInAnyOrder`?
