### ISSUE TITLE
Make shouldNotBe smarter by using contracts

### ISSUE THREAD

**Issue by Zefz** [kotest/kotest#986]
If we use `shouldNotBe` to match with `null` then maybe we could help the compiler infer null-safety for successive code.

```
foo shouldNotBe null
foo.bar!! shouldBe "bar"
```
would become
```
foo shouldNotBe null
foo.bar shouldBe "bar"
```

A similar solution that already uses contracts:
```
foo.shouldNotBeNull()
foo.bar shouldBe "bar"
```

Basically this minor enhancement would make 
`value shouldNotBe null` 
synonymous with 
`value.shouldNotBeNull()`.

I would prefer using the former infix for test code readability.

**Comment by LeoColman** [comment]
Unfortunately, this doesn't work yet, AFAIK.

It's not possible to make a conditional check in a contract, such as `if x is null, return implies y not null`.

This is possible with the extension function because we can say `returns implies x not null`.

Until there's a change in contracts (I don't believe this kind of contract will be supported soon), I don't believe there's much we can do.
